// words.js - File khusus untuk daftar kata
// Anda bisa menambahkan kata baru di sini dengan format:
// { eng: "kata_inggris", idn: "artinya", ex: "contoh kalimat" },

const fullVocab = [
    { eng: "apple", idn: "apel", ex: "I eat a red apple." },
    { eng: "house", idn: "rumah", ex: "My house is big." },
    { eng: "water", idn: "air", ex: "I drink water." },
    { eng: "book", idn: "buku", ex: "I read a book." },
    { eng: "school", idn: "sekolah", ex: "I go to school." },
    { eng: "happy", idn: "senang", ex: "She is very happy." },
    { eng: "small", idn: "kecil", ex: "The mouse is small." },
    { eng: "big", idn: "besar", ex: "The elephant is big." },
    { eng: "friend", idn: "teman", ex: "He is my friend." },
    { eng: "morning", idn: "pagi", ex: "Good morning!" },
    { eng: "night", idn: "malam", ex: "The stars shine at night." },
    { eng: "beautiful", idn: "cantik", ex: "The flower is beautiful." },
    { eng: "cold", idn: "dingin", ex: "Ice is very cold." },
    { eng: "hot", idn: "panas", ex: "The sun is hot." },
    { eng: "hungry", idn: "lapar", ex: "I am hungry for food." },
    { eng: "run", idn: "lari", ex: "I run in the park." },
    { eng: "write", idn: "menulis", ex: "Write your name." },
    { eng: "mother", idn: "ibu", ex: "I love my mother." },
    { eng: "father", idn: "ayah", ex: "My father is working." },
    { eng: "table", idn: "meja", ex: "The book is on the table." },
    { eng: "chair", idn: "kursi", ex: "Sit on the chair." },
    { eng: "green", idn: "hijau", ex: "The grass is green." },
    { eng: "yellow", idn: "kuning", ex: "The banana is yellow." },
    { eng: "fast", idn: "cepat", ex: "The car is fast." },
    { eng: "slow", idn: "lambat", ex: "The turtle is slow." },
    { eng: "animal", idn: "hewan", ex: "A dog is an animal." },
    { eng: "bird", idn: "burung", ex: "The bird flies high." },
    { eng: "fish", idn: "ikan", ex: "Fish swim in water." },
    { eng: "tree", idn: "pohon", ex: "The tree is tall." },
    { eng: "city", idn: "kota", ex: "Jakarta is a big city." },
    { eng: "window", idn: "jendela", ex: "Open the window." },
    { eng: "door", idn: "pintu", ex: "Close the door." },
    { eng: "car", idn: "mobil", ex: "He drives a car." },
    { eng: "bike", idn: "sepeda", ex: "I ride my bike." },
    { eng: "bus", idn: "bis", ex: "The bus is late." },
    { eng: "train", idn: "kereta", ex: "The train is long." },
    { eng: "sun", idn: "matahari", ex: "The sun is yellow." },
    { eng: "moon", idn: "bulan", ex: "The moon is round." },
    { eng: "star", idn: "bintang", ex: "I see a star." },
    { eng: "rain", idn: "hujan", ex: "I like the rain." },
    { eng: "mountain", idn: "gunung", ex: "The mountain is high." },
    { eng: "sea", idn: "laut", ex: "The sea is blue." },
    { eng: "beach", idn: "pantai", ex: "Let's go to the beach." },
    { eng: "sky", idn: "langit", ex: "The sky is blue." },
    { eng: "head", idn: "kepala", ex: "My head hurts." },
    { eng: "hand", idn: "tangan", ex: "Wash your hands." },
    { eng: "foot", idn: "kaki", ex: "My foot is small." },
    { eng: "eye", idn: "mata", ex: "I see with my eyes." },
    { eng: "milk", idn: "susu", ex: "I drink milk." },
    { eng: "egg", idn: "telur", ex: "I like boiled eggs." },
    { eng: "fruit", idn: "buah", ex: "Mango is a fruit." },
    { eng: "sweet", idn: "manis", ex: "Candy is sweet." },
    { eng: "clean", idn: "bersih", ex: "The room is clean." },
    { eng: "dirty", idn: "kotor", ex: "Your shirt is dirty." },
    { eng: "new", idn: "baru", ex: "I have a new toy." },
    { eng: "old", idn: "tua", ex: "The car is old." },
    { eng: "sad", idn: "sedih", ex: "Don't be sad." },
    { eng: "tired", idn: "lelah", ex: "I am tired now." },
    { eng: "angry", idn: "marah", ex: "The man is angry." },
    { eng: "sleepy", idn: "mengantuk", ex: "I am sleepy." },
    { eng: "strong", idn: "kuat", ex: "He is a strong boy." },
    { eng: "weak", idn: "lemah", ex: "The bridge is weak." },
    { eng: "rich", idn: "kaya", ex: "The king is rich." },
    { eng: "poor", idn: "miskin", ex: "He is a poor man." },
    { eng: "work", idn: "bekerja", ex: "I work every day." },
    { eng: "play", idn: "bermain", ex: "Let's play football." },
    { eng: "laugh", idn: "tertawa", ex: "The baby laughs." },
    { eng: "cry", idn: "menangis", ex: "Don't cry." },
    { eng: "read", idn: "membaca", ex: "I read news." },
    { eng: "dance", idn: "menari", ex: "She can dance." },
    { eng: "sing", idn: "menyanyi", ex: "I sing a song." },
    { eng: "cook", idn: "memasak", ex: "Mom cooks rice." },
    { eng: "buy", idn: "membeli", ex: "I buy an apple." },
    { eng: "give", idn: "memberi", ex: "Give me the pen." },
    { eng: "take", idn: "mengambil", ex: "Take the book." },
    { eng: "open", idn: "membuka", ex: "Open the box." },
    { eng: "close", idn: "menutup", ex: "Close the book." },
    { eng: "help", idn: "menolong", ex: "Can you help me?" },
    { eng: "listen", idn: "mendengar", ex: "Listen to me." },
    { eng: "see", idn: "melihat", ex: "I see a bird." },
    { eng: "speak", idn: "berbicara", ex: "Speak slowly." },
    { eng: "walk", idn: "berjalan", ex: "I walk to work." },
    { eng: "swim", idn: "berenang", ex: "I can swim." },
    { eng: "wait", idn: "menunggu", ex: "Wait for me." },
    { eng: "find", idn: "menemukan", ex: "I find my key." },
    { eng: "lose", idn: "hilang", ex: "I lose my bag." },
    { eng: "bring", idn: "membawa", ex: "Bring your book." },
    { eng: "send", idn: "mengirim", ex: "Send a message." },
    { eng: "call", idn: "memanggil", ex: "Call my name." },
    { eng: "ask", idn: "bertanya", ex: "Ask the teacher." },
    { eng: "know", idn: "tahu", ex: "I know the way." },
    { eng: "think", idn: "berpikir", ex: "Think about it." },
    { eng: "forget", idn: "lupa", ex: "Don't forget." },
    { eng: "learn", idn: "belajar", ex: "Learn English." },
    { eng: "black", idn: "hitam", ex: "My hair is black." },
    { eng: "white", idn: "putih", ex: "The milk is white." },
    { eng: "red", idn: "merah", ex: "The apple is red." },
    { eng: "blue", idn: "biru", ex: "The sea is blue." },
    { eng: "one", idn: "satu", ex: "I have one cat." },
    { eng: "two", idn: "dua", ex: "Two birds fly." },
    { eng: "ten", idn: "sepuluh", ex: "I have ten fingers." },
    { eng: "day", idn: "hari", ex: "Today is a sunny day." },
    { eng: "week", idn: "minggu", ex: "Seven days in a week." },
    { eng: "year", idn: "tahun", ex: "Happy New Year." },
    { eng: "time", idn: "waktu", ex: "What time is it?" },
    { eng: "today", idn: "hari ini", ex: "Today is Monday." },
    { eng: "now", idn: "sekarang", ex: "Do it now." },
    { eng: "always", idn: "selalu", ex: "I always study." },
    { eng: "never", idn: "tidak pernah", ex: "I never lie." },
    { eng: "here", idn: "disini", ex: "Come here." },
    { eng: "there", idn: "disana", ex: "Go there." },
    { eng: "up", idn: "atas", ex: "Look up." },
    { eng: "down", idn: "bawah", ex: "Sit down." },
    { eng: "near", idn: "dekat", ex: "The park is near." },
    { eng: "far", idn: "jauh", ex: "The moon is far." },
    { eng: "good", idn: "baik", ex: "You are good." },
    { eng: "bad", idn: "buruk", ex: "The food is bad." },
    { eng: "easy", idn: "mudah", ex: "The test is easy." },
    { eng: "hard", idn: "sulit", ex: "Math is hard." },
    { eng: "yes", idn: "ya", ex: "Yes, I am." },
    { eng: "no", idn: "tidak", ex: "No, thank you." },
    { eng: "name", idn: "nama", ex: "What is your name?" },
    { eng: "family", idn: "keluarga", ex: "I love my family." },
    { eng: "money", idn: "uang", ex: "I have no money." },
    { eng: "food", idn: "makanan", ex: "I like spicy food." },
    { eng: "salt", idn: "garam", ex: "The salt is white." },
    { eng: "rice", idn: "nasi", ex: "I eat rice." },
    { eng: "soup", idn: "sup", ex: "The soup is hot." },
    { eng: "coffee", idn: "kopi", ex: "I drink coffee." },
    { eng: "tea", idn: "teh", ex: "I like hot tea." },
    { eng: "cup", idn: "cangkir", ex: "A cup of tea." },
    { eng: "plate", idn: "piring", ex: "Clean the plate." },
    { eng: "spoon", idn: "sendok", ex: "Eat with a spoon." },
    { eng: "shirt", idn: "kemeja", ex: "Wear a shirt." },
    { eng: "shoes", idn: "sepatu", ex: "Wear your shoes." },
    { eng: "bag", idn: "tas", ex: "This is my bag." },
    { eng: "phone", idn: "telepon", ex: "Answer the phone." },
    { eng: "paper", idn: "kertas", ex: "Write on paper." },
    { eng: "pen", idn: "pena", ex: "I use a pen." },
    { eng: "key", idn: "kunci", ex: "I find my key." },
    { eng: "bed", idn: "tempat tidur", ex: "Go to bed." },
    { eng: "flower", idn: "bunga", ex: "The flower smells good." },
    { eng: "road", idn: "jalan", ex: "The road is long." },
    { eng: "ball", idn: "bola", ex: "Kick the ball." },
    { eng: "toy", idn: "mainan", ex: "This is my toy." },
    { eng: "song", idn: "lagu", ex: "Sing a song." },
    { eng: "body", idn: "tubuh", ex: "Wash your body." },
    { eng: "dream", idn: "mimpi", ex: "I had a dream." },
    { eng: "life", idn: "hidup", ex: "Life is good." },
    { eng: "man", idn: "pria", ex: "The man is tall." },
    { eng: "woman", idn: "wanita", ex: "The woman is kind." },
    { eng: "child", id: "anak", ex: "The child is crying." },
    { eng: "people", idn: "orang", ex: "Many people are here." },
    { eng: "wind", idn: "angin", ex: "The wind is cold." },
    { eng: "cloud", idn: "awan", ex: "The cloud is white." },
    { eng: "snow", idn: "salju", ex: "The snow is cold." },
    { eng: "brother", idn: "kakak/adik laki-laki", ex: "He is my brother." },
    { eng: "sister", idn: "kakak/adik perempuan", ex: "She is my sister." },
    { eng: "uncle", idn: "paman", ex: "My uncle is tall." },
    { eng: "aunt", idn: "bibi", ex: "My aunt is kind." },
    { eng: "cousin", idn: "sepupu", ex: "I play with my cousin." },
    { eng: "son", idn: "anak laki-laki", ex: "He is my son." },
    { eng: "daughter", idn: "anak perempuan", ex: "She is my daughter." },
    { eng: "bread", idn: "roti", ex: "I eat bread." },
    { eng: "butter", idn: "mentega", ex: "I like butter." },
    { eng: "cheese", idn: "keju", ex: "The cheese is yellow." },
    { eng: "meat", idn: "daging", ex: "I cook meat." },
    { eng: "chicken", idn: "ayam", ex: "I like fried chicken." },
    { eng: "duck", idn: "bebek", ex: "The duck swims." },
    { eng: "eggplant", idn: "terong", ex: "I like eggplant." },
    { eng: "garlic", idn: "bawang putih", ex: "I use garlic." },
    { eng: "onion", idn: "bawang merah", ex: "Chop the onion." },
    { eng: "potato", idn: "kentang", ex: "I like potato." },
    { eng: "tomato", idn: "tomat", ex: "The tomato is red." },
    { eng: "carrot", idn: "wortel", ex: "Eat your carrot." },
    { eng: "lemon", idn: "lemon", ex: "The lemon is sour." },
    { eng: "orange", idn: "jeruk", ex: "The orange is sweet." },
    { eng: "grape", idn: "anggur", ex: "The grape is purple." },
    { eng: "melon", idn: "melon", ex: "The melon is green." },
    { eng: "banana", idn: "pisang", ex: "Eat a banana." },
    { eng: "pineapple", idn: "nanas", ex: "The pineapple is yellow." },
    { eng: "dog", idn: "anjing", ex: "The dog barks." },
    { eng: "cat", idn: "kucing", ex: "The cat meows." },
    { eng: "cow", idn: "sapi", ex: "The cow gives milk." },
    { eng: "horse", idn: "kuda", ex: "The horse runs." },
    { eng: "sheep", idn: "domba", ex: "The sheep is white." },
    { eng: "goat", idn: "kambing", ex: "The goat eats grass." },
    { eng: "pig", idn: "babi", ex: "The pig is pink." },
    { eng: "rabbit", idn: "kelinci", ex: "The rabbit hops." },
    { eng: "mouse", idn: "tikus", ex: "The mouse is small." },
    { eng: "lion", idn: "singa", ex: "The lion is strong." },
    { eng: "tiger", idn: "harimau", ex: "The tiger is fast." },
    { eng: "elephant", idn: "gajah", ex: "The elephant is big." },
    { eng: "monkey", idn: "monyet", ex: "The monkey climbs." },
    { eng: "snake", idn: "ular", ex: "The snake crawls." },
    { eng: "ant", idn: "semut", ex: "The ant is small." },
    { eng: "bee", idn: "lebah", ex: "The bee flies." },
    { eng: "spider", idn: "laba-laba", ex: "The spider spins." },
    { eng: "fly", idn: "lalat", ex: "The fly is annoying." },
    { eng: "mouth", idn: "mulut", ex: "Open your mouth." },
    { eng: "nose", idn: "hidung", ex: "Breathe through your nose." },
    { eng: "ear", idn: "telinga", ex: "Listen with your ears." },
    { eng: "hair", idn: "rambut", ex: "My hair is long." },
    { eng: "tooth", idn: "gigi", ex: "Brush your teeth." },
    { eng: "neck", idn: "leher", ex: "Wash your neck." },
    { eng: "arm", idn: "lengan", ex: "Raise your arm." },
    { eng: "finger", idn: "jari", ex: "Point your finger." },
    { eng: "leg", idn: "kaki", ex: "Move your leg." },
    { eng: "knee", idn: "lutut", ex: "Bend your knee." },
    { eng: "toe", idn: "jari kaki", ex: "Touch your toe." },
    { eng: "heart", idn: "jantung", ex: "My heart beats." },
    { eng: "stomach", idn: "perut", ex: "My stomach hurts." },
    { eng: "blood", idn: "darah", ex: "The blood is red." },
    { eng: "skin", idn: "kulit", ex: "Wash your skin." },
    { eng: "bone", idn: "tulang", ex: "The bone is hard." },
    { eng: "shirt", idn: "kemeja", ex: "I wear a shirt." },
    { eng: "pants", idn: "celana", ex: "Put on your pants." },
    { eng: "dress", idn: "gaun", ex: "The dress is blue." },
    { eng: "skirt", idn: "rok", ex: "The skirt is short." },
    { eng: "jacket", idn: "jaket", ex: "Wear a jacket." },
    { eng: "socks", idn: "kaos kaki", ex: "My socks are red." },
    { eng: "shoes", idn: "sepatu", ex: "Wear your shoes." },
    { eng: "hat", idn: "topi", ex: "Wear a hat." },
    { eng: "gloves", idn: "sarung tangan", ex: "Wear your gloves." },
    { eng: "belt", idn: "ikat pinggang", ex: "Use a belt." },
    { eng: "tie", idn: "dasi", ex: "Wear a tie." },
    { eng: "glasses", idn: "kacamata", ex: "I use glasses." },
    { eng: "watch", idn: "jam tangan", ex: "Look at your watch." },
    { eng: "ring", idn: "cincin", ex: "The ring is gold." },
    { eng: "necklace", idn: "kalung", ex: "The necklace is pretty." },
    { eng: "bracelet", idn: "gelang", ex: "The bracelet is silver." },
    { eng: "umbrella", idn: "payung", ex: "Use an umbrella." },
    { eng: "wallet", idn: "dompet", ex: "My wallet is empty." },
    { eng: "money", idn: "uang", ex: "I have some money." },
    { eng: "mirror", idn: "cermin", ex: "Look in the mirror." },
    { eng: "comb", idn: "sisir", ex: "Use a comb." },
    { eng: "brush", idn: "sikat", ex: "Use a brush." },
    { eng: "soap", idn: "sabun", ex: "Wash with soap." },
    { eng: "shampoo", idn: "sampo", ex: "Use shampoo." },
    { eng: "towel", idn: "handuk", ex: "Use a towel." },
    { eng: "toothbrush", idn: "sikat gigi", ex: "Use a toothbrush." },
    { eng: "toothpaste", idn: "pasta gigi", ex: "Use toothpaste." },
    { eng: "razor", idn: "pisau cukur", ex: "Be careful with a razor." },
    { eng: "perfume", idn: "parfum", ex: "The perfume smells good." },
    { eng: "cream", idn: "krim", ex: "Use some cream." },
    { eng: "scissors", idn: "gunting", ex: "Cut with scissors." },
    { eng: "needle", idn: "jarum", ex: "Use a needle." },
    { eng: "thread", idn: "benang", ex: "The thread is long." },
    { eng: "button", idn: "kancing", ex: "The button is small." },
    { eng: "knife", idn: "pisau", ex: "Be careful with a knife." },
    { eng: "fork", idn: "garpu", ex: "Eat with a fork." },
    { eng: "spoon", idn: "sendok", ex: "Eat with a spoon." },
    { eng: "pan", idn: "panci", ex: "Mom uses a pan." },
    { eng: "pot", idn: "kuali", ex: "The pot is hot." },
    { eng: "oven", idn: "oven", ex: "Bake in the oven." },
    { eng: "refrigerator", idn: "kulkas", ex: "The refrigerator is cold." },
    { eng: "sink", idn: "wastafel", ex: "Wash in the sink." },
    { eng: "toilet", idn: "toilet", ex: "Go to the toilet." },
    { eng: "shower", idn: "shower", ex: "Take a shower." },
    { eng: "bath", idn: "mandi", ex: "Take a bath." },
    { eng: "room", idn: "kamar", ex: "The room is clean." },
    { eng: "bedroom", idn: "kamar tidur", ex: "Sleep in the bedroom." },
    { eng: "kitchen", idn: "dapur", ex: "Cook in the kitchen." },
    { eng: "bathroom", idn: "kamar mandi", ex: "Wash in the bathroom." },
    { eng: "living room", idn: "ruang tamu", ex: "Sit in the living room." },
    { eng: "garden", idn: "kebun", ex: "Play in the garden." },
    { eng: "wall", idn: "dinding", ex: "The wall is white." },
    { eng: "floor", idn: "lantai", ex: "Sweep the floor." },
    { eng: "ceiling", idn: "langit-langit", ex: "Look at the ceiling." },
    { eng: "roof", idn: "atap", ex: "The roof is high." },
    { eng: "stairs", idn: "tangga", ex: "Climb the stairs." },
    { eng: "gate", idn: "gerbang", ex: "Open the gate." },
    { eng: "fence", idn: "pagar", ex: "The fence is tall." },
    { eng: "window", idn: "jendela", ex: "The window is open." },
    { eng: "curtain", idn: "tirai", ex: "Close the curtain." },
    { eng: "lamp", idn: "lampu", ex: "Turn on the lamp." },
    { eng: "light", idn: "cahaya", ex: "The light is bright." },
    { eng: "fan", idn: "kipas angin", ex: "Turn on the fan." },
    { eng: "radio", idn: "radio", ex: "Listen to the radio." },
    { eng: "television", idn: "televisi", ex: "Watch television." },
    { eng: "computer", idn: "komputer", ex: "I use a computer." },
    { eng: "keyboard", idn: "keyboard", ex: "Type on the keyboard." },
    { eng: "mouse", idn: "mouse", ex: "Click the mouse." },
    { eng: "screen", idn: "layar", ex: "Look at the screen." },
    { eng: "printer", idn: "printer", ex: "Use the printer." },
    { eng: "paper", idn: "kertas", ex: "I need some paper." },
    { eng: "pen", idn: "pena", ex: "I write with a pen." },
    { eng: "pencil", idn: "pensil", ex: "I draw with a pencil." },
    { eng: "eraser", idn: "penghapus", ex: "Use an eraser." },
    { eng: "ruler", idn: "penggaris", ex: "Measure with a ruler." },
    { eng: "book", idn: "buku", ex: "I read a book." },
    { eng: "notebook", idn: "buku catatan", ex: "Write in your notebook." },
    { eng: "bag", idn: "tas", ex: "Put it in your bag." },
    { eng: "desk", idn: "meja tulis", ex: "Sit at your desk." },
    { eng: "teacher", idn: "guru", ex: "Listen to the teacher." },
    { eng: "student", idn: "murid", ex: "I am a student." },
    { eng: "class", idn: "kelas", ex: "I go to class." },
    { eng: "lesson", idn: "pelajaran", ex: "Study your lesson." },
    { eng: "exam", idn: "ujian", ex: "I have an exam." },
    { eng: "question", idn: "pertanyaan", ex: "Ask a question." },
    { eng: "answer", idn: "jawaban", ex: "Write the answer." },
    { eng: "pencil case", idn: "tempat pensil", ex: "Put it in the pencil case." },
    { eng: "lunch", idn: "makan siang", ex: "Eat your lunch." },
    { eng: "recess", idn: "istirahat", ex: "Play during recess." },
    { eng: "library", idn: "perpustakaan", ex: "Read in the library." },
    { eng: "bookcase", idn: "rak buku", ex: "Put it on the bookcase." },
    { eng: "blackboard", idn: "papan tulis", ex: "Look at the blackboard." },
    { eng: "chalk", idn: "kapur", ex: "Write with chalk." },
    { eng: "marker", idn: "spidol", ex: "Use a marker." },
    { eng: "map", idn: "peta", ex: "Look at the map." },
    { eng: "globe", idn: "bola dunia", ex: "Find it on the globe." },
    { eng: "glue", idn: "lem", ex: "Use some glue." },
    { eng: "tape", idn: "selotip", ex: "Use some tape." },
    { eng: "calculator", idn: "kalkulator", ex: "Use a calculator." },
    { eng: "clock", idn: "jam", ex: "Look at the clock." },
    { eng: "calendar", idn: "kalender", ex: "Look at the calendar." },
    { eng: "flag", idn: "bendera", ex: "The flag is red." },
    { eng: "paper clip", idn: "penjepit kertas", ex: "Use a paper clip." },
    { eng: "stapler", idn: "stapler", ex: "Use the stapler." },
    { eng: "folder", idn: "map", ex: "Put it in the folder." },
    { eng: "envelope", idn: "amplop", ex: "Put it in an envelope." },
    { eng: "stamp", idn: "perangko", ex: "Use a stamp." },
    { eng: "letter", idn: "surat", ex: "Write a letter." },
    { eng: "mail", idn: "surat", ex: "Check the mail." },
    { eng: "package", idn: "paket", ex: "I have a package." },
    { eng: "box", idn: "kotak", ex: "Put it in the box." },
    { eng: "telephone", idn: "telepon", ex: "Answer the telephone." },
    { eng: "cell phone", idn: "telepon seluler", ex: "Check your cell phone." },
    { eng: "camera", idn: "kamera", ex: "Take a picture." },
    { eng: "photo", idn: "foto", ex: "Look at the photo." },
    { eng: "video", idn: "video", ex: "Watch a video." },
    { eng: "movie", idn: "film", ex: "Watch a movie." },
    { eng: "music", idn: "musik", ex: "Listen to music." },
    { eng: "song", idn: "lagu", ex: "Sing a song." },
    { eng: "dance", idn: "tarian", ex: "Learn a dance." },
    { eng: "game", idn: "permainan", ex: "Play a game." },
    { eng: "sport", idn: "olahraga", ex: "I like sport." },
    { eng: "team", idn: "tim", ex: "Join the team." },
    { eng: "player", idn: "pemain", ex: "I am a player." },
    { eng: "ball", idn: "bola", ex: "Kick the ball." },
    { eng: "bat", idn: "pemukul", ex: "Use the bat." },
    { eng: "goal", idn: "gol", ex: "Score a goal." },
    { eng: "win", idn: "menang", ex: "Try to win." },
    { eng: "lose", idn: "kalah", ex: "Try not to lose." },
    { eng: "jump", idn: "melompat", ex: "Can you jump?" },
    { eng: "run", idn: "berlari", ex: "Can you run?" },
    { eng: "walk", idn: "berjalan", ex: "Can you walk?" },
    { eng: "climb", idn: "memanjat", ex: "Can you climb?" },
    { eng: "swim", idn: "berenang", ex: "Can you swim?" },
    { eng: "ride", idn: "mengendarai", ex: "Can you ride?" },
    { eng: "drive", idn: "mengemudi", ex: "Can you drive?" },
    { eng: "fly", idn: "terbang", ex: "Can you fly?" },
    { eng: "eat", idn: "makan", ex: "Can you eat?" },
    { eng: "drink", idn: "minum", ex: "Can you drink?" },
    { eng: "sleep", idn: "tidur", ex: "Can you sleep?" },
    { eng: "dream", idn: "bermimpi", ex: "Can you dream?" },
    { eng: "laugh", idn: "tertawa", ex: "Can you laugh?" },
    { eng: "cry", idn: "menangis", ex: "Can you cry?" },
    { eng: "smile", idn: "tersenyum", ex: "Can you smile?" },
    { eng: "shout", idn: "berteriak", ex: "Can you shout?" },
    { eng: "whisper", idn: "berbisik", ex: "Can you whisper?" },
    { eng: "sing", idn: "menyanyi", ex: "Can you sing?" },
    { eng: "dance", idn: "menari", ex: "Can you dance?" },
    { eng: "write", idn: "menulis", ex: "Can you write?" },
    { eng: "read", idn: "membaca", ex: "Can you read?" },
    { eng: "draw", idn: "menggambar", ex: "Can you draw?" },
    { eng: "paint", idn: "melukis", ex: "Can you paint?" },
    { eng: "think", idn: "berpikir", ex: "Can you think?" },
    { eng: "learn", idn: "belajar", ex: "Can you learn?" },
    { eng: "study", idn: "belajar", ex: "Can you study?" },
    { eng: "know", idn: "tahu", ex: "Can you know?" },
    { eng: "forget", idn: "lupa", ex: "Can you forget?" },
    { eng: "remember", idn: "ingat", ex: "Can you remember?" },
    { eng: "open", idn: "membuka", ex: "Can you open?" },
    { eng: "close", idn: "menutup", ex: "Can you close?" },
    { eng: "stop", idn: "berhenti", ex: "Can you stop?" },
    { eng: "start", idn: "mulai", ex: "Can you start?" },
    { eng: "end", idn: "berakhir", ex: "Can you end?" },
    { eng: "work", idn: "bekerja", ex: "Can you work?" },
    { eng: "play", idn: "bermain", ex: "Can you play?" },
    { eng: "help", idn: "menolong", ex: "Can you help?" },
    { eng: "give", idn: "memberi", ex: "Can you give?" },
    { eng: "take", idn: "mengambil", ex: "Can you take?" },
    { eng: "bring", idn: "membawa", ex: "Can you bring?" },
    { eng: "send", idn: "mengirim", ex: "Can you send?" },
    { eng: "get", idn: "mendapatkan", ex: "Can you get?" },
    { eng: "find", idn: "menemukan", ex: "Can you find?" },
    { eng: "lose", idn: "kehilangan", ex: "Can you lose?" },
    { eng: "win", idn: "menang", ex: "Can you win?" },
    { eng: "hot", idn: "panas", ex: "It is hot." },
    { eng: "cold", idn: "dingin", ex: "It is cold." },
    { eng: "warm", idn: "hangat", ex: "It is warm." },
    { eng: "cool", idn: "sejuk", ex: "It is cool." },
    { eng: "dry", idn: "kering", ex: "It is dry." },
    { eng: "wet", idn: "basah", ex: "It is wet." },
    { eng: "bright", idn: "terang", ex: "It is bright." },
    { eng: "dark", idn: "gelap", ex: "It is dark." },
    { eng: "clean", idn: "bersih", ex: "It is clean." },
    { eng: "dirty", idn: "kotor", ex: "It is dirty." },
    { eng: "fast", idn: "cepat", ex: "It is fast." },
    { eng: "slow", idn: "lambat", ex: "It is slow." },
    { eng: "easy", idn: "mudah", ex: "It is easy." },
    { eng: "hard", idn: "sulit", ex: "It is hard." },
    { eng: "strong", idn: "kuat", ex: "He is strong." },
    { eng: "weak", idn: "lemah", ex: "He is weak." },
    { eng: "rich", idn: "kaya", ex: "They are rich." },
    { eng: "poor", idn: "miskin", ex: "They are poor." },
    { eng: "happy", idn: "senang", ex: "I am happy." },
    { eng: "sad", idn: "sedih", ex: "I am sad." },
    { eng: "angry", idn: "marah", ex: "I am angry." },
    { eng: "scared", idn: "takut", ex: "I am scared." },
    { eng: "brave", idn: "berani", ex: "I am brave." },
    { eng: "tall", idn: "tinggi", ex: "The boy is tall." },
    { eng: "short", idn: "pendek", ex: "The boy is short." },
    { eng: "fat", idn: "gemuk", ex: "The cat is fat." },
    { eng: "thin", idn: "kurus", ex: "The cat is thin." },
    { eng: "large", idn: "luas", ex: "The room is large." },
    { eng: "small", idn: "kecil", ex: "The room is small." },
    { eng: "long", idn: "panjang", ex: "The rope is long." },
    { eng: "short", idn: "pendek", ex: "The rope is short." },
    { eng: "heavy", idn: "berat", ex: "The box is heavy." },
    { eng: "light", idn: "ringan", ex: "The box is light." },
    { eng: "thick", idn: "tebal", ex: "The book is thick." },
    { eng: "thin", idn: "tipis", ex: "The book is thin." },
    { eng: "sharp", idn: "tajam", ex: "The knife is sharp." },
    { eng: "dull", idn: "tumpul", ex: "The knife is dull." },
    { eng: "soft", idn: "lembut", ex: "The pillow is soft." },
    { eng: "hard", idn: "keras", ex: "The stone is hard." },
    { eng: "sweet", idn: "manis", ex: "The fruit is sweet." },
    { eng: "sour", idn: "asam", ex: "The fruit is sour." },
    { eng: "bitter", idn: "pahit", ex: "The coffee is bitter." },
    { eng: "salty", idn: "asin", ex: "The soup is salty." },
    { eng: "spicy", idn: "pedas", ex: "The food is spicy." }
];