 const fullVocab =[
        { idn: "Singkat / Sementara", eng: "ephemeral", ex: "The beauty of the sunset was ephemeral, fading within minutes." },
        { idn: "Bertele-tele / Cerewet", eng: "loquacious", ex: "The loquacious professor talked for three hours without a break." },
        { idn: "Sangat teliti / Cermat", eng: "meticulous", ex: "She is meticulous about keeping her lab records accurate." },
        { idn: "Meredakan / Menenangkan", eng: "mollify", ex: "He tried to mollify the angry customer by offering a refund." },
        { idn: "Berani / Lancang", eng: "audacious", ex: "The student made an audacious request to change the exam date." },
        { idn: "Keras kepala / Teguh", eng: "tenacious", ex: "His tenacious spirit helped him recover from the injury quickly." },
        { idn: "Sombong / Angkuh", eng: "haughty", ex: "Her haughty attitude made it difficult for her to make friends." },
        { idn: "Cepat berubah / Tidak menentu", eng: "capricious", ex: "The weather in April is capricious, sunny one moment and raining the next." },
        { idn: "Penyangkalan diri", eng: "abnegation", ex: "Monks practice abnegation, giving up worldly pleasures." },
        { idn: "Kebencian yang mendalam", eng: "animosity", ex: "There is no animosity between the two rival teams off the field." },
        { idn: "Sangat pedas / Tajam (kritik)", eng: "acerbic", ex: "His acerbic comments about the movie upset the director." },
        { idn: "Malu-malu / Penakut", eng: "timorous", ex: "The timorous child hid behind his mother's leg." },
        { idn: "Bersifat merusak", eng: "pernicious", ex: "Smoking has a pernicious effect on long-term health." },
        { idn: "Hemat / Sederhana", eng: "frugal", ex: "He is frugal with his money, rarely eating at expensive restaurants." },
        { idn: "Kuno / Usang", eng: "archaic", ex: "The factory used archaic machinery that often broke down." },
        { idn: "Mudah berubah / Tidak stabil", eng: "volatile", ex: "The stock market is volatile, with prices swinging wildly." },
        { idn: "Sangat gembira", eng: "euphoric", ex: "The team was euphoric after winning the championship." },
        { idn: "Membingungkan", eng: "enigmatic", ex: "The Mona Lisa has an enigmatic smile that puzzles viewers." },
        { idn: "Suka berkelahi", eng: "pugnacious", ex: "The pugnacious dog barked at every stranger who passed by." },
        { idn: "Bersifat memuji secara berlebihan", eng: "adulatory", ex: "The adulatory review praised every aspect of the performance." },
        { idn: "Tidak mementingkan diri sendiri", eng: "altruistic", ex: "Her altruistic nature led her to volunteer at the shelter." },
        { idn: "Kekuatan atau semangat", eng: "alacrity", ex: "He accepted the job offer with alacrity and enthusiasm." },
        { idn: "Meringankan / Mengurangi", eng: "alleviate", ex: "Take this medicine to alleviate your headache." },
        { idn: "Sangat buruk / Keji", eng: "egregious", ex: "The referee made an egregious error that cost them the game." },
        { idn: "Menghapuskan / Memusnahkan", eng: "expunge", ex: "The lawyer tried to expunge the crime from his client's record." },
        { idn: "Berlebihan / Mubazir", eng: "superfluous", ex: "Please delete the superfluous details to keep the report concise." },
        { idn: "Kurang ajar / Tidak sopan", eng: "insolent", ex: "The insolent student talked back to the teacher." },
        { idn: "Tebal muka / Tidak tahu malu", eng: "impudent", ex: "It was impudent of him to ask for a raise on his first day." },
        { idn: "Sulit dipahami", eng: "abstruse", ex: "The philosopher's theories were too abstruse for the general public." },
        { idn: "Sangat lapar / Rakus", eng: "ravenous", ex: "After the hike, we were ravenous and ate everything." },
        { idn: "Penuh rahasia", eng: "clandestine", ex: "They held a clandestine meeting to discuss the merger." },
        { idn: "Sopan / Ramah", eng: "affable", ex: "The manager is an affable person who is easy to talk to." },
        { idn: "Kebingungan / Dilema", eng: "quandary", ex: "I am in a quandary about which university to choose." },
        { idn: "Menghormati", eng: "venerate", ex: "People venerate the old professor for his wisdom." },
        { idn: "Singkat dan padat", eng: "laconic", ex: "His laconic reply suggested he was not interested in talking." },
        { idn: "Mendukung / Memperkuat", eng: "corroborate", ex: "The witness can corroborate the suspect's alibi." },
        { idn: "Kurang energi / Lesu", eng: "lethargic", ex: "The hot weather made everyone feel lethargic and slow." },
        { idn: "Sangat mahir", eng: "adept", ex: "She is adept at solving complex mathematical problems." },
        { idn: "Menhasut / Memicu", eng: "instigate", ex: "Don't instigate a fight by shouting insults." },
        { idn: "Sesuatu yang menyimpang", eng: "aberration", ex: "The sudden drop in temperature was an aberration for this season." },
        { idn: "Mengutuk / Sangat membenci", eng: "abhor", ex: "I abhor violence in any form." },
        { idn: "Setuju tanpa protes", eng: "acquiesce", ex: "She decided to acquiesce to her boss's demands to avoid conflict." },
        { idn: "Ketajaman pikiran", eng: "acumen", ex: "His business acumen helped him build a successful company." },
        { idn: "Teguran keras", eng: "admonition", ex: "He received a stern admonition for being late again." },
        { idn: "Kekayaan / Kelimpahan", eng: "affluence", ex: "The neighborhood is known for its affluence and luxury homes." },
        { idn: "Memperbesar / Meningkatkan", eng: "aggrandize", ex: "The king sought to aggrandize his empire through conquest." },
        { idn: "Keraguan / Pertentangan perasaan", eng: "ambivalence", ex: "She felt some ambivalence about accepting the promotion." },
        { idn: "Memperbaiki", eng: "ameliorate", ex: "Foreign aid helped ameliorate the effects of the drought." },
        { idn: "Ramah / Damai", eng: "amiable", ex: "Our new neighbor is an amiable man who always waves hello." },
        { idn: "Ketidakteraturan / Kejanggalan", eng: "anomaly", ex: "The data showed an anomaly that couldn't be explained." },
        { idn: "Kebencian / Antipati", eng: "antipathy", ex: "There is a strong antipathy between the two political parties." },
        { idn: "Puncak / Titik tertinggi", eng: "apex", ex: "At the apex of his career, he was the most famous actor in the world." },
        { idn: "Menenangkan (pihak lawan)", eng: "appease", ex: "The government tried to appease the protesters by lowering taxes." },
        { idn: "Sewenang-wenang", eng: "arbitrary", ex: "The decision to close the park seemed arbitrary and unfair." },
        { idn: "Semangat / Gairah", eng: "ardor", ex: "He spoke with great ardor about his love for literature." },
        { idn: "Sangat sulit / Melelahkan", eng: "arduous", ex: "Climbing the mountain was an arduous task." },
        { idn: "Mengetahui / Memastikan", eng: "ascertain", ex: "The police tried to ascertain the cause of the accident." },
        { idn: "Sangat hemat / Bertapa", eng: "ascetic", ex: "The monk lived an ascetic life with few possessions." },
        { idn: "Ketekunan", eng: "assiduity", ex: "She studied with great assiduity to pass the exam." },
        { idn: "Meredakan (rasa sakit/takut)", eng: "assuage", ex: "The doctor tried to assuage the patient's fears." },
        { idn: "Keberanian yang lancang", eng: "audacity", ex: "I can't believe he had the audacity to lie to my face." },
        { idn: "Pertanda baik", eng: "auspicious", ex: "The clear blue sky was an auspicious start to the wedding day." },
        { idn: "Keras / Sederhana tanpa hiasan", eng: "austere", ex: "The room was austere, containing only a bed and a chair." },
        { idn: "Keserakahan", eng: "avarice", ex: "His avarice led him to cheat his business partners." },
        { idn: "Menyatakan dengan yakin", eng: "aver", ex: "The witness continued to aver that he saw the defendant leaving." },
        { idn: "Membosankan / Biasa saja", eng: "banal", ex: "The movie's plot was banal and predictable." },
        { idn: "Menipu / Memperdaya", eng: "beguile", ex: "The salesman used charm to beguile customers into buying useless items." },
        { idn: "Bertentangan dengan", eng: "belie", ex: "Her calm smile belied the anger she felt inside." },
        { idn: "Bersikap ramah / Baik hati", eng: "benevolent", ex: "The benevolent donor gave millions to charity." },
        { idn: "Bias / Kecenderungan", eng: "bias", ex: "The referee showed a clear bias against our team." },
        { idn: "Kasihan / Kebisingan", eng: "cacophony", ex: "The classroom was filled with a cacophony of shouting children." },
        { idn: "Terus terang / Jujur", eng: "candid", ex: "Please give me your candid opinion about my presentation." },
        { idn: "Mencela / Menegur keras", eng: "castigate", ex: "The media castigated the official for his corruption." },
        { idn: "Katalis / Pemercepat", eng: "catalyst", ex: "The protest became a catalyst for political change." },
        { idn: "Bersifat tajam / Menyakiti hati", eng: "caustic", ex: "He is known for his caustic wit and sarcastic remarks." },
        { idn: "Berhati-hati / Waspada", eng: "circumspect", ex: "We must be circumspect when discussing confidential matters." },
        { idn: "Paksaan", eng: "coercion", ex: "The confession was obtained under police coercion." },
        { idn: "Masuk akal / Meyakinkan", eng: "cogent", ex: "She presented a cogent argument for why we should cut costs." },
        { idn: "Sesuai dengan", eng: "commensurate", ex: "Your salary will be commensurate with your experience." },
        { idn: "Keluhan / Ketidakpuasan", eng: "complacence", ex: "We cannot afford complacence; we must keep improving." },
        { idn: "Ringkas / Padat", eng: "concise", ex: "Make your summary concise and to the point." },
        { idn: "Mengampuni / Memaklumi", eng: "condone", ex: "The school does not condone bullying of any kind." },
        { idn: "Pertemuan / Penggabungan", eng: "confluence", ex: "The city was built at the confluence of two rivers." },
        { idn: "Menyimpulkan", eng: "conjecture", ex: "Without evidence, your theory is just pure conjecture." },
        { idn: "Menghargai / Ahli", eng: "connoisseur", ex: "He is a connoisseur of fine wines." },
        { idn: "Membuat suci / Mengabdikan", eng: "consecrate", ex: "The church was consecrated in 1890." },
        { idn: "Isi / Pendapat", eng: "contention", ex: "It is my contention that the policy is flawed." },
        { idn: "Menyesal", eng: "contrite", ex: "The boy looked contrite after breaking the vase." },
        { idn: "Teka-teki", eng: "conundrum", ex: "Solving this math problem is a real conundrum." },
        { idn: "Berliku-liku / Rumit", eng: "convoluted", ex: "The instructions were so convoluted that I gave up." },
        { idn: "Melimpah", eng: "copious", ex: "She took copious notes during the lecture." },
        { idn: "Menginginkan milik orang lain", eng: "covetous", ex: "He looked at his neighbor's new car with covetous eyes." },
        { idn: "Mudah percaya", eng: "credulous", ex: "The credulous tourists bought the fake souvenirs." },
        { idn: "Kesopanan / Kepatutan", eng: "decorum", ex: "You must behave with decorum in the courtroom." },
        { idn: "Berbahaya / Merugikan", eng: "deleterious", ex: "Pollution has a deleterious impact on the environment." },
        { idn: "Menggambarkan", eng: "delineate", ex: "The contract clearly delineates the responsibilities of each party." },
        { idn: "Menolak / Memprotes", eng: "demur", ex: "She demurred when asked to work overtime on the weekend." },
        { idn: "Meremehkan", eng: "denigrate", ex: "Don't denigrate people just because they are different from you." },
        { idn: "Mengejek", eng: "deride", ex: "The critics derided the movie as a waste of time." },
        { idn: "Kering / Tidak bersemangat", eng: "desiccated", ex: "The landscape was desiccated after months of drought." },
        { idn: "Sangat miskin", eng: "destitute", ex: "The war left thousands of families destitute." },
        { idn: "Sepintas lalu / Tidak niat", eng: "desultory", ex: "He made a desultory attempt to clean his room." },
        { idn: "Sangat menghalangi", eng: "deterrent", ex: "High fines act as a deterrent to speeding." },
        { idn: "Penyimpangan", eng: "digression", ex: "After a brief digression, the speaker returned to the main topic." },
        { idn: "Ketajaman / Kecerdasan", eng: "discernment", ex: "She showed great discernment in choosing her investments." },
        { idn: "Berbeda / Tidak sama", eng: "disparate", ex: "The group was made up of people with disparate backgrounds." },
        { idn: "Menyebarkan (informasi)", eng: "disseminate", ex: "The internet helps disseminate information quickly." },
        { idn: "Berselisih", eng: "dissonance", ex: "There is cognitive dissonance between his beliefs and his actions." },
        { idn: "Mudah diatur", eng: "docile", ex: "The docile horse was easy for the child to ride." },
        { idn: "Keras kepala dalam keyakinan", eng: "dogmatic", ex: "He is so dogmatic that he refuses to listen to other opinions." },
        { idn: "Bermuka dua", eng: "duplicity", ex: "The spy was punished for his duplicity and betrayal." },
        { idn: "Aktif dan bertenaga", eng: "ebullient", ex: "The ebullient host made everyone feel welcome." },
        { idn: "Menyusun / Memperbaiki", eng: "edify", ex: "The book is intended to edify readers about history." },
        { idn: "Keberhasilan / Kemanjuran", eng: "efficacy", ex: "The efficacy of the new drug has not yet been proven." },
        { idn: "Kelemahan (karena usia)", eng: "effrontery", ex: "He had the effrontery to ask for a loan after losing my money." },
        { idn: "Berlebihan (pujian/emosi)", eng: "effusive", ex: "She gave an effusive welcome to the visiting dignitaries." },
        { idn: "Menghilangkan", eng: "elicit", ex: "The teacher tried to elicit an answer from the shy student." },
        { idn: "Fasih berbicara", eng: "eloquent", ex: "The politician gave an eloquent speech that moved the crowd." },
        { idn: "Melemahkan", eng: "enervate", ex: "The extreme heat enervated the runners." },
        { idn: "Menimbulkan / Menyebabkan", eng: "engender", ex: "Hatred engenders violence." },
        { idn: "Dendam / Kebencian", eng: "enmity", ex: "The peace treaty ended decades of enmity between the nations." },
        { idn: "Singkat", eng: "ephemeral", ex: "Fashions are ephemeral, changing with every season." },
        { idn: "Ketenangan jiwa", eng: "equanimity", ex: "He accepted the bad news with surprising equanimity." },
        { idn: "Ambigu / Tidak jelas", eng: "equivocal", ex: "The politician gave an equivocal answer to avoid taking a side." },
        { idn: "Sangat terpelajar", eng: "erudite", ex: "The erudite professor has read thousands of books." },
        { idn: "Menghindari", eng: "eschew", ex: "He eschews unhealthy foods and exercises daily." },
        { idn: "Hanya dipahami segelintir orang", eng: "esoteric", ex: "Quantum physics is an esoteric subject for many people." },
        { idn: "Memuji / Menyanjung", eng: "eulogize", ex: "Friends eulogized the actor at his funeral." },
        { idn: "Memperburuk (keadaan)", eng: "exacerbate", ex: "Scratching the itch will only exacerbate the rash." },
        { idn: "Menuntut secara paksa", eng: "exacting", ex: "The exacting standards of the chef ensured high-quality food." },
        { idn: "Membebaskan dari tuduhan", eng: "exculpate", ex: "DNA evidence helped exculpate the innocent man." },
        { idn: "Sangat mendesak", eng: "exigent", ex: "The exigent situation required immediate action." },
        { idn: "Membebaskan", eng: "exonerate", ex: "The report exonerated the pilot from any blame." },
        { idn: "Menjelaskan secara rinci", eng: "expound", ex: "The professor expounded on the theory of relativity." },
        { idn: "Masih ada (belum punah)", eng: "extant", ex: "The oldest extant manuscript dates back to the 10th century." },
        { idn: "Sangat memuji", eng: "extol", ex: "She extolled the virtues of a vegetarian diet." },
        { idn: "Luar biasa / Tidak relevan", eng: "extraneous", ex: "Please remove the extraneous information from your essay." },
        { idn: "Sangat riang", eng: "exuberant", ex: "The exuberant puppy jumped up and down." },
        { idn: "Memudahkan", eng: "facilitate", ex: "The new software will facilitate better communication." },
        { idn: "Keliru / Sesat", eng: "fallacious", ex: "His argument was based on fallacious reasoning." },
        { idn: "Sangat teliti / Rewel", eng: "fastidious", ex: "He is fastidious about his appearance and always looks sharp." },
        { idn: "Konyol / Bodoh", eng: "fatuous", ex: "He made a fatuous comment that embarrassed everyone." },
        { idn: "Kepatuhan / Loyalitas", eng: "fealty", ex: "The knights swore fealty to the king." },
        { idn: "Sangat bersemangat", eng: "fervid", ex: "She is a fervid supporter of animal rights." },
        { idn: "Kebiasaan buruk / Cacat", eng: "foible", ex: "We all have our little foibles and quirks." },
        { idn: "Mencegah / Menghalangi", eng: "forestall", ex: "Negotiations were held to forestall a strike." },
        { idn: "Kebetulan / Beruntung", eng: "fortuitous", ex: "The meeting was a fortuitous coincidence." },
        { idn: "Mudah pecah / Galak", eng: "fractious", ex: "The fractious crowd began to push against the barriers." },
        { idn: "Banyak bicara", eng: "garrulous", ex: "The garrulous taxi driver talked the entire ride." },
        { idn: "Relevan / Sesuai", eng: "germane", ex: "Please keep your comments germane to the topic." },
        { idn: "Lancar bicara (tapi tidak tulus)", eng: "glib", ex: "His glib apology did not sound sincere." },
        { idn: "Sombong / Angkuh", eng: "haughty", ex: "She gave him a haughty look and walked away." },
        { idn: "Pemuja kesenangan", eng: "hedonist", ex: "As a hedonist, he spent his money on parties and luxury." },
        { idn: "Penyimpangan agama / Tradisi", eng: "heresy", ex: "Galileo's ideas were considered heresy at the time." },
        { idn: "Sangat banyak / Seragam", eng: "homogeneous", ex: "The population of the village is remarkably homogeneous." },
        { idn: "Berlebihan (dalam bahasa)", eng: "hyperbole", ex: "Saying 'I'm starving' when you're just hungry is hyperbole." },
        { idn: "Munafik", eng: "hypocritical", ex: "It's hypocritical to criticize others for what you do yourself." },
        { idn: "Sifat aneh seseorang", eng: "idiosyncrasy", ex: "One of his idiosyncrasies is talking to his plants." },
        { idn: "Sangat memalukan", eng: "ignominious", ex: "The team suffered an ignominious defeat." },
        { idn: "Murni / Sempurna", eng: "immaculate", ex: "Her house is always immaculate." },
        { idn: "Berubah-ubah", eng: "immutable", ex: "The laws of physics are immutable." },
        { idn: "Tidak memihak", eng: "impartial", ex: "A judge must remain impartial during the trial." },
        { idn: "Sangat tenang", eng: "imperturbable", ex: "Even in the crisis, the captain remained imperturbable." },
        { idn: "Sangat miskin", eng: "impecunious", ex: "The impecunious student could not afford textbooks." },
        { idn: "Menghalangi", eng: "impede", ex: "Heavy traffic impeded our progress to the airport." },
        { idn: "Mendesak / Segera", eng: "imperative", ex: "It is imperative that you see a doctor immediately." },
        { idn: "Tenang / Tidak mudah marah", eng: "impassive", ex: "His face remained impassive as the verdict was read." },
        { idn: "Tergesa-gesa", eng: "impetuous", ex: "He made an impetuous decision to buy the car." },
        { idn: "Tidak henti-hentinya", eng: "implacable", ex: "The implacable enemy refused to surrender." },
        { idn: "Tersirat", eng: "implicit", ex: "There was an implicit understanding that we would share the cost." },
        { idn: "Kurang ajar", eng: "impudent", ex: "The impudent child stuck his tongue out." },
        { idn: "Menyanggah / Menyerang", eng: "impugn", ex: "Do not impugn my integrity with false accusations." },
        { idn: "Baru saja dimulai", eng: "inchoate", ex: "Her ideas for the project were still inchoate." },
        { idn: "Tidak peka / Tajam", eng: "incisive", ex: "The journalist asked incisive questions." },
        { idn: "Tidak serasi", eng: "incongruous", ex: "The modern furniture looked incongruous in the old castle." },
        { idn: "Tidak dapat disangkal", eng: "indisputable", ex: "The evidence of his guilt is indisputable." },
        { idn: "Malas", eng: "indolent", ex: "The indolent cat slept in the sun all day." },
        { idn: "Tidak dapat digambarkan", eng: "ineffable", ex: "The beauty of the landscape was ineffable." },
        { idn: "Keras hati", eng: "inexorable", ex: "The inexorable march of time affects us all." },
        { idn: "Naif / Jujur", eng: "ingenuous", ex: "She gave an ingenuous smile." },
        { idn: "Melekat", eng: "inherent", ex: "Risk is inherent in any investment." },
        { idn: "Berbahaya secara halus", eng: "insidious", ex: "Gum disease is an insidious problem." },
        { idn: "Membosankan / Tawar", eng: "insipid", ex: "The soup was insipid and needed salt." },
        { idn: "Menghasut", eng: "instigate", ex: "He was accused of instigating the riot." },
        { idn: "Teguh pendirian", eng: "intransigent", ex: "The union remained intransigent on the issue of wages." },
        { idn: "Sangat pemberani", eng: "intrepid", ex: "The intrepid explorer ventured into the jungle." },
        { idn: "Membanjiri", eng: "inundate", ex: "The office was inundated with complaints." },
        { idn: "Cepat marah", eng: "irascible", ex: "The old man was irascible and grumpy." },
        { idn: "Sangat teliti / Hati-hati", eng: "judicious", ex: "Make a judicious choice when selecting your courses." },
        { idn: "Memuji", eng: "laud", ex: "The critics lauded the movie as a masterpiece." },
        { idn: "Pemurah / Dermawan", eng: "magnanimous", ex: "He was magnanimous in victory, shaking his opponent's hand." },
        { idn: "Keinginan jahat", eng: "malevolence", ex: "There was a look of malevolence in his eyes." },
        { idn: "Dapat ditempa / Mudah dibentuk", eng: "malleable", ex: "Gold is a malleable metal." },
        { idn: "Sepele / Biasa", eng: "mundane", ex: "She wanted to escape her mundane daily routine." },
        { idn: "Sangat kecil", eng: "minuscule", ex: "The chances of winning are minuscule." },
        { idn: "Meremehkan", eng: "negligible", ex: "The difference in price is negligible." },
        { idn: "Terkenal jahat", eng: "notorious", ex: "The city is notorious for its traffic jams." },
        { idn: "Pemula", eng: "novice", ex: "He is a novice at chess." },
        { idn: "Sangat patuh", eng: "obsequious", ex: "The waiter was obsequious, constantly bowing." },
        { idn: "Keras kepala", eng: "obstinate", ex: "The obstinate mule refused to move." },
        { idn: "Menghilangkan / Mencegah", eng: "obviate", ex: "The new bridge obviated the need for a ferry." },
        { idn: "Menutup / Menghalangi", eng: "occlude", ex: "A blood clot can occlude a major artery." },
        { idn: "Sangat menjengkelkan", eng: "odious", ex: "The dictator was an odious tyrant." },
        { idn: "Beban", eng: "onus", ex: "The onus is on you to prove your innocence." },
        { idn: "Buram / Sulit dimengerti", eng: "opaque", ex: "The window was opaque with dirt." },
        { idn: "Mencolok / Pamer", eng: "ostentatious", ex: "She wore an ostentatious diamond necklace." },
        { idn: "Kesan yang jelas", eng: "palpable", ex: "The tension in the room was palpable." },
        { idn: "Obat segala penyakit", eng: "panacea", ex: "There is no single panacea for the world's problems." },
        { idn: "Paradoks / Bertentangan", eng: "paradox", ex: "It is a paradox that computers save time but we are busier than ever." },
        { idn: "Kikir / Sangat hemat", eng: "parsimonious", ex: "The parsimonious owner refused to pay for repairs." },
        { idn: "Sedikit", eng: "paucity", ex: "There is a paucity of information on the subject." },
        { idn: "Suka pamer ilmu", eng: "pedantic", ex: "His pedantic lectures were boring." },
        { idn: "Kecenderungan", eng: "penchant", ex: "She has a penchant for spicy food." },
        { idn: "Sangat miskin", eng: "penurious", ex: "He died a penurious old man." },
        { idn: "Singkat dan bermakna", eng: "pithy", ex: "His speech was full of pithy quotes." },
        { idn: "Menenangkan", eng: "placate", ex: "She bought a toy to placate the crying child." },
        { idn: "Biasa / Klise", eng: "platitude", ex: "He offered only empty platitudes." },
        { idn: "Sangat banyak", eng: "plethora", ex: "There is a plethora of options to choose from." },
        { idn: "Mempunyai beban berat (tugas)", eng: "ponderous", ex: "He walked with heavy, ponderous steps." },
        { idn: "Pragmatis", eng: "pragmatic", ex: "We need a pragmatic solution to the crisis." },
        { idn: "Labil / Tidak aman", eng: "precarious", ex: "The ladder was in a precarious position." },
        { idn: "Mendahului", eng: "preclude", ex: "His injury precluded him from playing in the final." },
        { idn: "Sangat berbakat sejak dini", eng: "precocious", ex: "The precocious child could read at age three." },
        { idn: "Predileksi / Kesukaan", eng: "predilection", ex: "He has a predilection for classical music." },
        { idn: "Keangkuhan", eng: "presumption", ex: "It is a presumption to think you know everything." },
        { idn: "Kejujuran", eng: "probity", ex: "The judge was known for his probity and fairness." },
        { idn: "Pemboros", eng: "prodigal", ex: "The prodigal son spent all his inheritance." },
        { idn: "Mendalam", eng: "profound", ex: "The book had a profound impact on me." },
        { idn: "Berkembang biak", eng: "proliferate", ex: "Rumors proliferated on the internet." },
        { idn: "Kecenderungan alami", eng: "propensity", ex: "He has a propensity for getting into trouble." },
        { idn: "Menenangkan hati", eng: "propitiate", ex: "They made offerings to propitiate the gods." },
        { idn: "Sesuai / Pantas", eng: "propriety", ex: "She behaved with the utmost propriety." },
        { idn: "Membosankan / Tidak puitis", eng: "prosaic", ex: "The view was rather prosaic." },
        { idn: "Berhati-hati / Bijaksana", eng: "prudent", ex: "It is prudent to save money for emergencies." },
        { idn: "Kanak-kanak / Kekanak-kanakan", eng: "puerile", ex: "Stop making puerile jokes." },
        { idn: "Suka mengeluh", eng: "querulous", ex: "The querulous patient complained about everything." },
        { idn: "Sangat pendiam", eng: "reticent", ex: "He was reticent about his private life." },
        { idn: "Sangat hormat", eng: "reverent", ex: "A reverent silence filled the church." },
        { idn: "Sangat teliti / Keras", eng: "rigorous", ex: "The training program was rigorous." },
        { idn: "Kesehatan yang baik", eng: "salubrious", ex: "The mountain air is salubrious." },
        { idn: "Sangat penting / Menonjol", eng: "salient", ex: "Please summarize the salient points." },
        { idn: "Sanksi / Izin", eng: "sanction", ex: "The government sanctioned the new law." },
        { idn: "Optimis", eng: "sanguine", ex: "He is sanguine about the company's future." },
        { idn: "Sangat pelit", eng: "scanty", ex: "The evidence was scanty." },
        { idn: "Teliti / Jujur", eng: "scrupulous", ex: "He is scrupulous in his business dealings." },
        { idn: "Menghasut", eng: "sedition", ex: "He was arrested for sedition." },
        { idn: "Tenang", eng: "serene", ex: "The lake looked serene in the moonlight." },
        { idn: "Hamba / Budak", eng: "servile", ex: "He had a servile attitude toward his boss." },
        { idn: "Kaku / Tegas", eng: "stolid", ex: "He remained stolid despite the bad news." },
        { idn: "Luar biasa", eng: "sublime", ex: "The view from the top was sublime." },
        { idn: "Halus / Sulit dideteksi", eng: "subtle", ex: "There was a subtle change in his voice." },
        { idn: "Cemberut / Murung", eng: "sullen", ex: "The sullen teenager sat in the corner." },
        { idn: "Diam-diam", eng: "surreptitious", ex: "He took a surreptitious glance at his watch." },
        { idn: "Pendiam", eng: "taciturn", ex: "The taciturn cowboy said little." },
        { idn: "Tersirat", eng: "tacit", ex: "We had a tacit agreement not to talk about it." },
        { idn: "Gaya bahasa bombastis", eng: "turgid", ex: "The writer's style was turgid and boring." },
        { idn: "Meluas / Di mana-mana", eng: "ubiquitous", ex: "Smartphones are ubiquitous nowadays." },
        { idn: "Berasal dari luar", eng: "extrinsic", ex: "Extrinsic rewards like money can motivate employees." },
        { idn: "Kebenaran", eng: "veracity", ex: "We questioned the veracity of his story." },
        { idn: "Banyak kata-kata", eng: "verbose", ex: "His report was verbose and repetitive." },
        { idn: "Sangat benci", eng: "vituperate", ex: "He vituperated the referee for the bad call." },
        { idn: "Rakus", eng: "voracious", ex: "She is a voracious reader." },
        { idn: "Melemah secara bertahap", eng: "wane", ex: "His interest in the hobby began to wane." },
        { idn: "Berhati-hati", eng: "wary", ex: "Be wary of strangers offering gifts." },
        { idn: "Puncak / Titik tertinggi", eng: "zenith", ex: "The sun was at its zenith." }
    ];