const fullVocab =[
    { eng: "achieve", idn: "mencapai", ex: "You can achieve your goals." },
    { eng: "advantage", idn: "keuntungan", ex: "He has a big advantage." },
    { eng: "ambition", idn: "ambisi", ex: "Her ambition is to be a pilot." },
    { eng: "ancient", idn: "kuno", ex: "Rome is an ancient city." },
    { eng: "anxious", idn: "cemas", ex: "I feel anxious about the test." },
    { eng: "approve", idn: "menyetujui", ex: "My boss will approve the plan." },
    { eng: "artificial", idn: "buatan", ex: "This is artificial light." },
    { eng: "attitude", idn: "sikap", ex: "He has a positive attitude." },
    { eng: "audience", idn: "penonton", ex: "The audience clapped loudly." },
    { eng: "available", idn: "tersedia", ex: "Is this seat available?" },
    { eng: "average", idn: "rata-rata", ex: "The temperature is average." },
    { eng: "avoid", idn: "menghindari", ex: "Avoid eating too much sugar." },
    { eng: "baggage", idn: "bagasi", ex: "Where is my baggage?" },
    { eng: "behavior", idn: "tingkah laku", ex: "His behavior was very strange." },
    { eng: "benefit", idn: "manfaat", ex: "Exercise has many benefits." },
    { eng: "calculate", idn: "menghitung", ex: "Calculate the total cost." },
    { eng: "campaign", idn: "kampanye", ex: "The election campaign started." },
    { eng: "capacity", idn: "kapasitas", ex: "The stadium is at full capacity." },
    { eng: "caution", idn: "peringatan", ex: "Use caution when driving." },
    { eng: "celebrity", idn: "selebriti", ex: "She is a famous celebrity." },
    { eng: "challenge", idn: "tantangan", ex: "Learning English is a challenge." },
    { eng: "character", idn: "karakter", ex: "He is a man of good character." },
    { eng: "circumstance", idn: "keadaan", ex: "The circumstances have changed." },
    { eng: "citizen", idn: "warga negara", ex: "I am a citizen of Indonesia." },
    { eng: "climate", idn: "iklim", ex: "The climate here is tropical." },
    { eng: "collapse", idn: "runtuh", ex: "The building might collapse." },
    { eng: "colleague", idn: "rekan kerja", ex: "I work with my colleagues." },
    { eng: "collect", idn: "mengumpulkan", ex: "I collect old coins." },
    { eng: "combine", idn: "menggabungkan", ex: "Combine the blue and red." },
    { eng: "comfort", idn: "kenyamanan", ex: "I like the comfort of home." },
    { eng: "command", idn: "perintah", ex: "Wait for my command." },
    { eng: "commercial", idn: "komersial", ex: "This is a commercial flight." },
    { eng: "committee", idn: "panitia", ex: "The committee met today." },
    { eng: "community", idn: "komunitas", ex: "We live in a small community." },
    { eng: "compare", idn: "membandingkan", ex: "Compare these two phones." },
    { eng: "compete", idn: "bersaing", ex: "We compete in the race." },
    { eng: "complain", idn: "mengeluh", ex: "Don't complain about the food." },
    { eng: "complex", idn: "rumit", ex: "The math problem is complex." },
    { eng: "confirm", idn: "konfirmasi", ex: "Please confirm your flight." },
    { eng: "consequence", idn: "konsekuensi", ex: "Think about the consequence." },
    { eng: "consider", idn: "mempertimbangkan", ex: "Consider all the options." },
    { eng: "consist", idn: "terdiri dari", ex: "The team consists of five people." },
    { eng: "constant", idn: "konstan", ex: "He is in constant pain." },
    { eng: "consume", idn: "mengkonsumsi", ex: "We consume a lot of water." },
    { eng: "contact", idn: "kontak", ex: "Contact me tomorrow." },
    { eng: "contain", idn: "berisi", ex: "This box contains books." },
    { eng: "content", idn: "konten", ex: "The content of the book is good." },
    { eng: "continue", idn: "melanjutkan", ex: "Please continue reading." },
    { eng: "contribute", idn: "berkontribusi", ex: "Contribute to the charity." },
    { eng: "control", idn: "kontrol", ex: "I can control the machine." },
    { eng: "convenient", idn: "nyaman", ex: "This location is convenient." },
    { eng: "convince", idn: "meyakinkan", ex: "Convince her to stay." },
    { eng: "courage", idn: "keberanian", ex: "It takes courage to do that." },
    { eng: "create", idn: "membuat", ex: "Create a new account." },
    { eng: "creative", idn: "kreatif", ex: "She is a creative artist." },
    { eng: "creature", idn: "makhluk", ex: "Strange creatures live here." },
    { eng: "criticism", idn: "kritik", ex: "I accept your criticism." },
    { eng: "crowded", idn: "padat", ex: "The bus is very crowded." },
    { eng: "culture", idn: "budaya", ex: "Indonesia has a rich culture." },
    { eng: "curious", idn: "penasaran", ex: "I am curious about the news." },
    { eng: "currency", idn: "mata uang", ex: "What is the local currency?" },
    { eng: "damage", idn: "kerusakan", ex: "The storm caused damage." },
    { eng: "debate", idn: "debat", ex: "They had a long debate." },
    { eng: "decade", idn: "dekade", ex: "Ten years is a decade." },
    { eng: "declare", idn: "menyatakan", ex: "They declare war." },
    { eng: "decline", idn: "menurun", ex: "The prices will decline." },
    { eng: "decorate", idn: "menghias", ex: "Decorate the room for the party." },
    { eng: "decrease", idn: "berkurang", ex: "The population will decrease." },
    { eng: "defeat", idn: "mengalahkan", ex: "We will defeat the enemy." },
    { eng: "defense", idn: "pertahanan", ex: "The army is our defense." },
    { eng: "define", idn: "mendefinisikan", ex: "Define this word clearly." },
    { eng: "degree", idn: "gelar/derajat", ex: "I have a college degree." },
    { eng: "delay", idn: "penundaan", ex: "There is a flight delay." },
    { eng: "delicate", idn: "halus", ex: "The glass is very delicate." },
    { eng: "delivery", idn: "pengiriman", ex: "When is the food delivery?" },
    { eng: "demand", idn: "permintaan", ex: "There is a high demand for oil." },
    { eng: "demonstrate", idn: "mendemonstrasikan", ex: "Demonstrate how to use it." },
    { eng: "deny", idn: "menyangkal", ex: "He will deny the truth." },
    { eng: "depart", idn: "berangkat", ex: "The train will depart soon." },
    { eng: "depend", idn: "bergantung", ex: "It depends on the weather." },
    { eng: "describe", idn: "mendeskripsikan", ex: "Describe your home." },
    { eng: "deserve", idn: "layak", ex: "You deserve a prize." },
    { eng: "design", idn: "desain", ex: "I like the design of the car." },
    { eng: "desire", idn: "keinginan", ex: "My desire is to travel." },
    { eng: "destroy", idn: "menghancurkan", ex: "Don't destroy the forest." },
    { eng: "detail", idn: "detail", ex: "Explain it in detail." },
    { eng: "detect", idn: "mendeteksi", ex: "Can you detect a ghost?" },
    { eng: "determine", idn: "menentukan", ex: "Determine the answer." },
    { eng: "develop", idn: "mengembangkan", ex: "Develop a new plan." },
    { eng: "device", idn: "perangkat", ex: "This is a mobile device." },
    { eng: "diary", idn: "buku harian", ex: "I write in my diary." },
    { eng: "diet", idn: "diet", ex: "He is on a healthy diet." },
    { eng: "difference", idn: "perbedaan", ex: "What is the difference?" },
    { eng: "difficult", idn: "sulit", ex: "The test was difficult." },
    { eng: "dig", idn: "menggali", ex: "Dig a hole in the ground." },
    { eng: "direction", idn: "arah", ex: "Which direction should I go?" },
    { eng: "director", idn: "direktur", ex: "He is the director of the film." },
    { eng: "disadvantage", idn: "kerugian", ex: "Smoking is a disadvantage." },
    { eng: "disappear", idn: "menghilang", ex: "The sun will disappear." },
    { eng: "disappoint", idn: "mengecewakan", ex: "Don't disappoint your mom." },
    { eng: "disaster", idn: "bencana", ex: "The flood was a disaster." },
    { eng: "discover", idn: "menemukan", ex: "Discover a new land." },
    { eng: "discuss", idn: "mendiskusikan", ex: "Discuss the problem." },
    { eng: "disease", idn: "penyakit", ex: "Flu is a common disease." },
    { eng: "dislike", idn: "tidak suka", ex: "I dislike spicy food." },
    { eng: "dismiss", idn: "memberhentikan", ex: "Dismiss the class early." },
    { eng: "display", idn: "menampilkan", ex: "Display the results." },
    { eng: "distance", idn: "jarak", ex: "The distance is ten miles." },
    { eng: "distribute", idn: "mendistribusikan", ex: "Distribute the flyers." },
    { eng: "district", idn: "distrik", ex: "This is a shopping district." },
    { eng: "disturb", idn: "mengganggu", ex: "Do not disturb me." },
    { eng: "divide", idn: "membagi", ex: "Divide the cake in four." },
    { eng: "divorce", idn: "perceraian", ex: "They got a divorce." },
    { eng: "document", idn: "dokumen", ex: "Sign the document." },
    { eng: "domestic", idn: "domestik", ex: "Domestic animals live at home." },
    { eng: "donate", idn: "menyumbang", ex: "Donate blood today." },
    { eng: "doubt", idn: "ragu", ex: "I doubt it will rain." },
    { eng: "dozen", idn: "lusin", ex: "I buy a dozen eggs." },
    { eng: "drag", idn: "menyeret", ex: "Drag the chair here." },
    { eng: "drama", idn: "drama", ex: "I like watching drama." },
    { eng: "dramatic", idn: "dramatis", ex: "It was a dramatic change." },
    { eng: "dreadful", idn: "mengerikan", ex: "The news was dreadful." },
    { eng: "drown", idn: "tenggelam", ex: "Can you drown in a pool?" },
    { eng: "duty", idn: "tugas/kewajiban", ex: "It is my duty to help." },
    { eng: "eager", idn: "bersemangat", ex: "She is eager to start." },
    { eng: "earn", idn: "menghasilkan", ex: "Earn money by working." },
    { eng: "economic", idn: "ekonomi", ex: "The economic situation is bad." },
    { eng: "economy", idn: "ekonomi", ex: "The global economy is growing." },
    { eng: "edit", idn: "mengedit", ex: "Edit the video." },
    { eng: "education", idn: "pendidikan", ex: "Education is important." },
    { eng: "effect", idn: "efek", ex: "The drug has an effect." },
    { eng: "effective", idn: "efektif", ex: "This medicine is effective." },
    { eng: "effort", idn: "usaha", ex: "Make an effort to study." },
    { eng: "election", idn: "pemilihan", ex: "The presidential election." },
    { eng: "electric", idn: "listrik", ex: "I have an electric car." },
    { eng: "element", idn: "unsur", ex: "Water is an element of life." },
    { eng: "embarrass", idn: "memalukan", ex: "Don't embarrass me." },
    { eng: "emergency", idn: "darurat", ex: "Call 911 for emergency." },
    { eng: "emotion", idn: "emosi", ex: "Anger is an emotion." },
    { eng: "emphasis", idn: "penekanan", ex: "Put emphasis on the word." },
    { eng: "employ", idn: "mempekerjakan", ex: "They employ ten people." },
    { eng: "employee", idn: "karyawan", ex: "I am an employee here." },
    { eng: "employer", idn: "majikan", ex: "The employer is kind." },
    { eng: "employment", idn: "pekerjaan", ex: "Full-time employment." },
    { eng: "empty", idn: "kosong", ex: "The glass is empty." },
    { eng: "encourage", idn: "mendorong", ex: "Encourage your friends." },
    { eng: "energy", idn: "energi", ex: "I have no energy." },
    { eng: "engine", idn: "mesin", ex: "The car engine is noisy." },
    { eng: "engineer", idn: "insinyur", ex: "He is a software engineer." },
    { eng: "enormous", idn: "sangat besar", ex: "The house is enormous." },
    { eng: "enough", idn: "cukup", ex: "I have enough money." },
    { eng: "ensure", idn: "memastikan", ex: "Ensure the door is locked." },
    { eng: "entertain", idn: "menghibur", ex: "Entertain the guests." },
    { eng: "enthusiast", idn: "penggemar", ex: "I am a car enthusiast." },
    { eng: "entire", idn: "seluruh", ex: "I ate the entire pizza." },
    { eng: "environment", idn: "lingkungan", ex: "Protect the environment." },
    { eng: "episode", idn: "episode", ex: "Watch the next episode." },
    { eng: "equal", idn: "sama", ex: "All men are equal." },
    { eng: "equip", idn: "melengkapi", ex: "Equip the lab with tools." },
    { eng: "equipment", idn: "peralatan", ex: "Sports equipment." },
    { eng: "error", idn: "kesalahan", ex: "A system error occurred." },
    { eng: "escape", idn: "melarikan diri", ex: "Escape from the prison." },
    { eng: "essential", idn: "penting", ex: "Water is essential." },
    { eng: "establish", idn: "mendirikan", ex: "Establish a new company." },
    { eng: "estimate", idn: "memperkirakan", ex: "Estimate the price." },
    { eng: "event", idn: "acara", ex: "The wedding is a big event." },
    { eng: "evidence", idn: "bukti", ex: "There is no evidence." },
    { eng: "exact", idn: "tepat", ex: "The exact time is noon." },
    { eng: "examine", idn: "memeriksa", ex: "Examine the patient." },
    { eng: "excellent", idn: "luar biasa", ex: "Your work is excellent." },
    { eng: "exchange", idn: "pertukaran", ex: "Exchange the money." },
    { eng: "excite", idn: "menggairahkan", ex: "The news will excite you." },
    { eng: "exclude", idn: "mengecualikan", ex: "Exclude the tax." },
    { eng: "excuse", idn: "alasan", ex: "What is your excuse?" },
    { eng: "executive", idn: "eksekutif", ex: "He is an executive." },
    { eng: "exercise", idn: "olahraga", ex: "Morning exercise." },
    { eng: "exhibition", idn: "pameran", ex: "Art exhibition." },
    { eng: "exist", idn: "ada/eksis", ex: "Ghosts do not exist." },
    { eng: "expand", idn: "memperluas", ex: "Expand the business." },
    { eng: "expect", idn: "mengharapkan", ex: "I expect you to pass." },
    { eng: "expense", idn: "biaya", ex: "The expense is too high." },
    { eng: "expensive", idn: "mahal", ex: "Gold is expensive." },
    { eng: "experience", idn: "pengalaman", ex: "I have no experience." },
    { eng: "experiment", idn: "eksperimen", ex: "Science experiment." },
    { eng: "expert", idn: "ahli", ex: "He is a computer expert." },
    { eng: "explain", idn: "menjelaskan", ex: "Explain the rule." },
    { eng: "explore", idn: "menjelajah", ex: "Explore the ocean." },
    { eng: "export", idn: "ekspor", ex: "Export oil to China." },
    { eng: "express", idn: "mengekspresikan", ex: "Express your feelings." },
    { eng: "extend", idn: "memperpanjang", ex: "Extend the deadline." },
    { eng: "extra", idn: "tambahan", ex: "I need extra time." },
    { eng: "extreme", idn: "ekstrim", ex: "Extreme sports." },
    { eng: "factory", idn: "pabrik", ex: "I work in a factory." },
    { eng: "failure", idn: "kegagalan", ex: "Failure is a lesson." },
    { eng: "familiar", idn: "akrab", ex: "Your face looks familiar." },
    { eng: "famous", idn: "terkenal", ex: "Bali is famous." },
    { eng: "fashion", idn: "mode", ex: "She loves fashion." },
    { eng: "feature", idn: "fitur", ex: "A new feature of the app." },
    { eng: "federal", idn: "federal", ex: "Federal government." },
    { eng: "fee", idn: "biaya", ex: "Admission fee." },
    { eng: "feeling", idn: "perasaan", ex: "I have a good feeling." },
    { eng: "fellow", idn: "teman", ex: "My fellow students." },
    { eng: "female", idn: "perempuan", ex: "The cat is female." },
    { eng: "festival", idn: "festival", ex: "Music festival." },
    { eng: "fiction", idn: "fiksi", ex: "Science fiction book." },
    { eng: "field", idn: "lapangan", ex: "Rice field." },
    { eng: "figure", idn: "angka/sosok", ex: "A public figure." },
    { eng: "file", idn: "file", ex: "Save the file." },
    { eng: "fill", idn: "mengisi", ex: "Fill the bottle." },
    { eng: "final", idn: "final", ex: "The final match." },
    { eng: "finance", idn: "keuangan", ex: "Department of finance." },
    { eng: "financial", idn: "finansial", ex: "Financial support." },
    { eng: "firm", idn: "perusahaan/kokoh", ex: "Law firm." },
    { eng: "flavour", idn: "rasa", ex: "Vanilla flavour." },
    { eng: "float", idn: "mengapung", ex: "Wood can float." },
    { eng: "flood", idn: "banjir", ex: "The street is flood." },
    { eng: "flow", idn: "mengalir", ex: "River flow." },
    { eng: "focus", idn: "fokus", ex: "Focus on your work." },
    { eng: "fold", idn: "melipat", ex: "Fold the clothes." },
    { eng: "force", idn: "kekuatan/paksa", ex: "Police force." },
    { eng: "foreign", idn: "asing", ex: "Foreign language." },
    { eng: "forever", idn: "selamanya", ex: "Friends forever." },
    { eng: "formal", idn: "formal", ex: "Formal dress." },
    { eng: "formula", idn: "rumus", ex: "Math formula." },
    { eng: "fortune", idn: "keberuntungan", ex: "He has a big fortune." },
    { eng: "forward", idn: "maju/depan", ex: "Step forward." },
    { eng: "foundation", idn: "yayasan/dasar", ex: "Charity foundation." },
    { eng: "frame", idn: "bingkai", ex: "Photo frame." },
    { eng: "freeze", idn: "membeku", ex: "Water will freeze." },
    { eng: "frequent", idn: "sering", ex: "Frequent visitor." },
    { eng: "fresh", idn: "segar", ex: "Fresh milk." },
    { eng: "frighten", idn: "menakuti", ex: "Don't frighten me." },
    { eng: "fuel", idn: "bahan bakar", ex: "Car fuel." },
    { eng: "function", idn: "fungsi", ex: "Brain function." },
    { eng: "fund", idn: "dana", ex: "Scholarship fund." },
    { eng: "furniture", idn: "furnitur", ex: "New furniture." },
    { eng: "future", idn: "masa depan", ex: "In the future." },
    { eng: "gain", idn: "mendapatkan", ex: "Gain weight." },
    { eng: "gallery", idn: "galeri", ex: "Art gallery." },
    { eng: "gap", idn: "celah", ex: "A gap in the fence." },
    { eng: "garage", idn: "garasi", ex: "Park in the garage." },
    { eng: "gather", idn: "berkumpul", ex: "Gather around." },
    { eng: "general", idn: "umum", ex: "General knowledge." },
    { eng: "generate", idn: "menghasilkan", ex: "Generate electricity." },
    { eng: "generation", idn: "generasi", ex: "New generation." },
    { eng: "generous", idn: "dermawan", ex: "He is generous." },
    { eng: "gentle", idn: "lembut", ex: "Be gentle." },
    { eng: "genuine", idn: "asli", ex: "Genuine leather." },
    { eng: "gesture", idn: "isyarat", ex: "Hand gesture." },
    { eng: "ghost", idn: "hantu", ex: "Scary ghost." },
    { eng: "giant", idn: "raksasa", ex: "Giant building." },
    { eng: "glance", idn: "sekilas", ex: "At first glance." },
    { eng: "global", idn: "global", ex: "Global warming." },
    { eng: "glory", idn: "kejayaan", ex: "Glory of Rome." },
    { eng: "goal", idn: "tujuan", ex: "Score a goal." },
    { eng: "government", idn: "pemerintah", ex: "The government rules." },
    { eng: "grab", idn: "mengambil/merebut", ex: "Grab a snack." },
    { eng: "grade", idn: "nilai/tingkat", ex: "Good grade." },
    { eng: "gradual", idn: "bertahap", ex: "Gradual change." },
    { eng: "graduate", idn: "lulusan", ex: "College graduate." },
    { eng: "grain", idn: "butir/biji", ex: "Grain of rice." },
    { eng: "grand", idn: "megah", ex: "Grand hotel." },
    { eng: "grant", idn: "hibah/mengabulkan", ex: "Research grant." },
    { eng: "grateful", idn: "berterima kasih", ex: "I am grateful." },
    { eng: "gravity", idn: "gravitasi", ex: "Earth gravity." },
    { eng: "greed", idn: "keserakahan", ex: "Human greed." },
    { eng: "grocery", idn: "toko kelontong", ex: "Grocery store." },
    { eng: "ground", idn: "tanah", ex: "Sit on the ground." },
    { eng: "growth", idn: "pertumbuhan", ex: "Economic growth." },
    { eng: "guarantee", idn: "garansi", ex: "Money back guarantee." },
    { eng: "guard", idn: "penjaga", ex: "Security guard." },
    { eng: "guess", idn: "tebak", ex: "Guess who?" },
    { eng: "guest", idn: "tamu", ex: "Welcome our guest." },
    { eng: "guide", idn: "pemandu", ex: "Tour guide." },
    { eng: "guilty", idn: "bersalah", ex: "Feel guilty." },
    { eng: "habit", idn: "kebiasaan", ex: "Bad habit." },
    { eng: "handle", idn: "menangani", ex: "Handle with care." },
    { eng: "hang", idn: "menggantung", ex: "Hang the picture." },
    { eng: "harbour", idn: "pelabuhan", ex: "Ship at the harbour." },
    { eng: "hardly", idn: "hampir tidak", ex: "I hardly sleep." },
    { eng: "harm", idn: "bahaya/menyakiti", ex: "No harm." },
    { eng: "harvest", idn: "panen", ex: "Rice harvest." },
    { eng: "health", idn: "kesehatan", ex: "Health care." },
    { eng: "healthy", idn: "sehat", ex: "Healthy food." },
    { eng: "height", idn: "tinggi", ex: "Body height." },
    { eng: "hesitate", idn: "ragu-ragu", ex: "Don't hesitate." },
    { eng: "hidden", idn: "tersembunyi", ex: "Hidden treasure." },
    { eng: "hire", idn: "menyewa/mempekerjakan", ex: "Hire a car." },
    { eng: "history", idn: "sejarah", ex: "World history." },
    { eng: "honest", idn: "jujur", ex: "Be honest." },
    { eng: "honour", idn: "kehormatan", ex: "Sense of honour." },
    { eng: "hope", idn: "harapan", ex: "I hope so." },
    { eng: "horrible", idn: "mengerikan", ex: "Horrible dream." },
    { eng: "hospital", idn: "rumah sakit", ex: "Go to hospital." },
    { eng: "host", idn: "tuan rumah", ex: "Talk show host." },
    { eng: "huge", idn: "besar sekali", ex: "Huge elephant." },
    { eng: "humble", idn: "rendah hati", ex: "Stay humble." },
    { eng: "humour", idn: "humor", ex: "Sense of humour." },
    { eng: "hunt", idn: "berburu", ex: "Hunt for food." },
    { eng: "ideal", idn: "ideal", ex: "Ideal weight." },
    { eng: "identify", idn: "mengidentifikasi", ex: "Identify the suspect." },
    { eng: "ignore", idn: "mengabaikan", ex: "Ignore the noise." },
    { eng: "illegal", idn: "ilegal", ex: "Illegal drugs." },
    { eng: "illness", idn: "penyakit", ex: "Mental illness." },
    { eng: "illustrate", idn: "mengilustrasikan", ex: "Illustrate the book." },
    { eng: "image", idn: "gambar/citra", ex: "Public image." },
    { eng: "imagination", idn: "imajinasi", ex: "Power of imagination." },
    { eng: "imagine", idn: "membayangkan", ex: "Imagine that." },
    { eng: "immediate", idn: "segera", ex: "Immediate response." },
    { eng: "impact", idn: "dampak", ex: "Social impact." },
    { eng: "impatient", idn: "tidak sabar", ex: "Don't be impatient." },
    { eng: "implement", idn: "melaksanakan", ex: "Implement the law." },
    { eng: "imply", idn: "menyiratkan", ex: "What do you imply?" },
    { eng: "import", idn: "impor", ex: "Import sugar." },
    { eng: "importance", idn: "kepentingan", ex: "Matter of importance." },
    { eng: "impress", idn: "mengesankan", ex: "Impress your boss." },
    { eng: "impression", idn: "kesan", ex: "First impression." },
    { eng: "improve", idn: "meningkatkan", ex: "Improve English." },
    { eng: "improvement", idn: "peningkatan", ex: "Big improvement." },
    { eng: "incident", idn: "insiden", ex: "Road incident." },
    { eng: "include", idn: "termasuk", ex: "Tax included." },
    { eng: "income", idn: "pendapatan", ex: "Monthly income." },
    { eng: "increase", idn: "meningkatkan", ex: "Increase price." },
    { eng: "indeed", idn: "memang", ex: "Yes, indeed." },
    { eng: "independent", idn: "mandiri", ex: "Independent woman." },
    { eng: "indicate", idn: "menunjukkan", ex: "Signs indicate rain." },
    { eng: "individual", idn: "individu", ex: "Each individual." },
    { eng: "industry", idn: "industri", ex: "Music industry." },
    { eng: "inevitable", idn: "tidak bisa dihindari", ex: "Inevitable death." },
    { eng: "infection", idn: "infeksi", ex: "Skin infection." },
    { eng: "influence", idn: "pengaruh", ex: "Social influence." },
    { eng: "inform", idn: "menginformasikan", ex: "Inform the police." },
    { eng: "information", idn: "informasi", ex: "Need information." },
    { eng: "ingredient", idn: "bahan", ex: "Food ingredient." },
    { eng: "initial", idn: "awal", ex: "Initial stage." },
    { eng: "injury", idn: "cedera", ex: "Leg injury." },
    { eng: "inner", idn: "bagian dalam", ex: "Inner peace." },
    { eng: "innocent", idn: "tidak bersalah", ex: "Innocent child." },
    { eng: "insect", idn: "serangga", ex: "Tiny insect." },
    { eng: "inside", idn: "didalam", ex: "Go inside." },
    { eng: "insist", idn: "bersikeras", ex: "I insist." },
    { eng: "inspect", idn: "memeriksa", ex: "Inspect the house." },
    { eng: "install", idn: "memasang", ex: "Install app." },
    { eng: "instance", idn: "contoh", ex: "For instance." },
    { eng: "instant", idn: "instan", ex: "Instant noodle." },
    { eng: "instead", idn: "malah", ex: "Instead of water." },
    { eng: "instruct", idn: "menginstruksikan", ex: "Instruct the staff." },
    { eng: "instruction", idn: "instruksi", ex: "Read instruction." },
    { eng: "instrument", idn: "instrumen", ex: "Musical instrument." },
    { eng: "insurance", idn: "asuransi", ex: "Life insurance." },
    { eng: "intellectual", idn: "intelektual", ex: "Intellectual property." },
    { eng: "intelligence", idn: "kecerdasan", ex: "Artificial intelligence." },
    { eng: "intend", idn: "berniat", ex: "I intend to go." },
    { eng: "intent", idn: "niat", ex: "Criminal intent." },
    { eng: "intention", idn: "niat", ex: "Good intention." },
    { eng: "interest", idn: "bunga/minat", ex: "Bank interest." },
    { eng: "interior", idn: "interior", ex: "Interior design." },
    { eng: "internal", idn: "internal", ex: "Internal audit." },
    { eng: "international", idn: "internasional", ex: "International airport." },
    { eng: "interpret", idn: "menafsirkan", ex: "Interpret the dream." },
    { eng: "interrupt", idn: "menyela", ex: "Don't interrupt." },
    { eng: "interval", idn: "interval", ex: "Time interval." },
    { eng: "interview", idn: "wawancara", ex: "Job interview." },
    { eng: "introduce", idn: "memperkenalkan", ex: "Introduce yourself." },
    { eng: "introduction", idn: "pengantar", ex: "Introduction book." },
    { eng: "invent", idn: "menemukan/menciptakan", ex: "Invent new tool." },
    { eng: "invention", idn: "penemuan", ex: "Thomas Edison invention." },
    { eng: "invest", idn: "berinvestasi", ex: "Invest in gold." },
    { eng: "investigate", idn: "menyelidiki", ex: "Investigate the case." },
    { eng: "investment", idn: "investasi", ex: "Safe investment." },
    { eng: "invitation", idn: "undangan", ex: "Party invitation." },
    { eng: "invite", idn: "mengundang", ex: "Invite friends." },
    { eng: "involve", idn: "melibatkan", ex: "Involve the family." },
    { eng: "iron", idn: "besi/setrika", ex: "Iron bar." },
    { eng: "island", idn: "pulau", ex: "Tropical island." },
    { eng: "issue", idn: "isu/masalah", ex: "Social issue." },
    { eng: "item", idn: "item/barang", ex: "Five items." },
    { eng: "jacket", idn: "jaket", ex: "Wear jacket." },
    { eng: "jail", idn: "penjara", ex: "Go to jail." },
    { eng: "jam", idn: "selai/macet", ex: "Traffic jam." },
    { eng: "jar", idn: "toples", ex: "Cookie jar." },
    { eng: "jaw", idn: "rahang", ex: "Lower jaw." },
    { eng: "jealous", idn: "cemburu", ex: "Don't be jealous." },
    { eng: "jeans", idn: "jeans", ex: "Blue jeans." },
    { eng: "jelly", idn: "jeli", ex: "Fruit jelly." },
    { eng: "jet", idn: "jet", ex: "Private jet." },
    { eng: "jewel", idn: "permata", ex: "Crown jewel." },
    { eng: "job", idn: "pekerjaan", ex: "Good job." },
    { eng: "join", idn: "bergabung", ex: "Join the club." },
    { eng: "joint", idn: "sendi/bersama", ex: "Knee joint." },
    { eng: "joke", idn: "lelucon", ex: "Funny joke." },
    { eng: "journal", idn: "jurnal", ex: "Medical journal." },
    { eng: "journey", idn: "perjalanan", ex: "Long journey." },
    { eng: "joy", idn: "kegembiraan", ex: "Bundle of joy." },
    { eng: "judge", idn: "hakim/menilai", ex: "Judge me." },
    { eng: "judgment", idn: "penilaian", ex: "Good judgment." },
    { eng: "juice", idn: "jus", ex: "Orange juice." },
    { eng: "jump", idn: "melompat", ex: "Jump high." },
    { eng: "junior", idn: "junior", ex: "Junior high." },
    { eng: "jury", idn: "dewan juri", ex: "Jury trial." },
    { eng: "just", idn: "adil/baru saja", ex: "Just arrived." },
    { eng: "justice", idn: "keadilan", ex: "Social justice." },
    { eng: "justify", idn: "membenarkan", ex: "Justify the action." },
    { eng: "keen", idn: "tekun/tajam", ex: "Keen interest." },
    { eng: "keep", idn: "menyimpan", ex: "Keep it safe." },
    { eng: "kettle", idn: "ketel", ex: "Tea kettle." },
    { eng: "key", idn: "kunci", ex: "Car key." },
    { eng: "kick", idn: "menendang", ex: "Kick the ball." },
    { eng: "kid", idn: "anak", ex: "Funny kid." },
    { eng: "kidnap", idn: "menculik", ex: "Kidnap the boy." },
    { eng: "kidney", idn: "ginjal", ex: "Left kidney." },
    { eng: "kill", idn: "membunuh", ex: "Kill the fly." },
    { eng: "kind", idn: "jenis/baik", ex: "What kind?" },
    { eng: "kingdom", idn: "kerajaan", ex: "Kingdom of Saudi." },
    { eng: "king", idn: "raja", ex: "Lion king." },
    { eng: "kiss", idn: "mencium", ex: "Kiss me." },
    { eng: "kitchen", idn: "dapur", ex: "In the kitchen." },
    { eng: "knee", idn: "lutut", ex: "Knee pain." },
    { eng: "knife", idn: "pisau", ex: "Sharp knife." },
    { eng: "knock", idn: "mengetuk", ex: "Knock the door." },
    { eng: "knot", idn: "simpul", ex: "Tie a knot." },
    { eng: "know", idn: "tahu", ex: "I know." },
    { eng: "knowledge", idn: "pengetahuan", ex: "General knowledge." },
    { eng: "label", idn: "label", ex: "Price label." },
    { eng: "laboratory", idn: "laboratorium", ex: "Science laboratory." },
    { eng: "labour", idn: "tenaga kerja", ex: "Manual labour." },
    { eng: "lack", idn: "kekurangan", ex: "Lack of sleep." },
    { eng: "ladder", idn: "tangga", ex: "Climb the ladder." },
    { eng: "lady", idn: "wanita", ex: "First lady." },
    { eng: "lake", idn: "danau", ex: "Toba lake." },
    { eng: "lamp", idn: "lampu", ex: "Desk lamp." },
    { eng: "land", idn: "tanah/mendarat", ex: "Land the plane." },
    { eng: "landscape", idn: "pemandangan", ex: "Beautiful landscape." },
    { eng: "language", idn: "bahasa", ex: "English language." },
    { eng: "lantern", idn: "lentera", ex: "Paper lantern." },
    { eng: "lap", idn: "pangkuan/putaran", ex: "Sit on my lap." },
    { eng: "large", idn: "besar", ex: "Large pizza." },
    { eng: "laser", idn: "laser", ex: "Laser pointer." },
    { eng: "last", idn: "terakhir", ex: "Last night." },
    { eng: "late", idn: "terlambat", ex: "Too late." },
    { eng: "lately", idn: "akhir-akhir ini", ex: "Lately I busy." },
    { eng: "later", idn: "nanti", ex: "See you later." },
    { eng: "latitude", idn: "garis lintang", ex: "North latitude." },
    { eng: "laugh", idn: "tertawa", ex: "Laugh out loud." },
    { eng: "launch", idn: "meluncurkan", ex: "Launch the rocket." },
    { eng: "laundry", idn: "cucian", ex: "Do the laundry." },
    { eng: "law", idn: "hukum", ex: "Break the law." },
    { eng: "lawyer", idn: "pengacara", ex: "Need a lawyer." },
    { eng: "lay", idn: "meletakkan", ex: "Lay the table." },
    { eng: "layer", idn: "lapisan", ex: "Ozone layer." },
    { eng: "lazy", idn: "malas", ex: "Lazy dog." },
    { eng: "lead", idn: "memimpin", ex: "Lead the team." },
    { eng: "leader", idn: "pemimpin", ex: "World leader." },
    { eng: "leaf", idn: "daun", ex: "Green leaf." },
    { eng: "league", idn: "liga", ex: "Premier league." },
    { eng: "leak", idn: "bocor", ex: "Water leak." },
    { eng: "lean", idn: "ramping/bersandar", ex: "Lean on me." },
    { eng: "learn", idn: "belajar", ex: "Learn more." },
    { eng: "least", idn: "sedikitnya", ex: "At least." },
    { eng: "leather", idn: "kulit", ex: "Leather jacket." },
    { eng: "leave", idn: "meninggalkan", ex: "Leave me alone." },
    { eng: "lecture", idn: "kuliah", ex: "Attend lecture." },
    { eng: "left", idn: "kiri/meninggalkan", ex: "Turn left." },
    { eng: "leg", idn: "kaki", ex: "Broken leg." },
    { eng: "legal", idn: "legal/hukum", ex: "Legal action." },
    { eng: "legend", idn: "legenda", ex: "Urban legend." },
    { eng: "leisure", idn: "waktu luang", ex: "Leisure time." },
    { eng: "lemon", idn: "lemon", ex: "Sour lemon." },
    { eng: "lend", idn: "meminjamkan", ex: "Lend me money." },
    { eng: "length", idn: "panjang", ex: "Bridge length." },
    { eng: "lens", idn: "lensa", ex: "Contact lens." },
    { eng: "less", idn: "kurang", ex: "Less sugar." },
    { eng: "lesson", idn: "pelajaran", ex: "English lesson." },
    { eng: "let", idn: "biarkan", ex: "Let it go." },
    { eng: "letter", idn: "surat/huruf", ex: "Capital letter." },
    { eng: "level", idn: "level/tingkat", ex: "Level up." },
    { eng: "liberal", idn: "liberal", ex: "Liberal arts." },
    { eng: "liberty", idn: "kebebasan", ex: "Statue of Liberty." },
    { eng: "library", idn: "perpustakaan", ex: "Public library." },
    { eng: "license", idn: "lisensi/sim", ex: "Driver license." },
    { eng: "lid", idn: "tutup", ex: "Eye lid." },
    { eng: "lie", idn: "berbohong/berbaring", ex: "Lie to me." },
    { eng: "life", idn: "hidup", ex: "My life." },
    { eng: "lift", idn: "mengangkat/lift", ex: "Take the lift." },
    { eng: "light", idn: "cahaya/ringan", ex: "Bright light." },
    { eng: "lightning", idn: "petir", ex: "Thunder and lightning." },
    { eng: "like", idn: "seperti/suka", ex: "I like you." },
    { eng: "likely", idn: "mungkin", ex: "Most likely." },
    { eng: "limit", idn: "batas", ex: "Speed limit." },
    { eng: "limited", idn: "terbatas", ex: "Limited edition." },
    { eng: "line", idn: "garis/baris", ex: "Wait in line." },
    { eng: "link", idn: "tautan/hubungkan", ex: "Check the link." },
    { eng: "lion", idn: "singa", ex: "Mountain lion." },
    { eng: "lip", idn: "bibir", ex: "Upper lip." },
    { eng: "liquid", idn: "cair", ex: "Liquid soap." },
    { eng: "list", idn: "daftar", ex: "Shopping list." },
    { eng: "listen", idn: "mendengar", ex: "Listen to music." },
    { eng: "literal", idn: "literal", ex: "Literal meaning." },
    { eng: "literary", idn: "literasi", ex: "Literary work." },
    { eng: "literature", idn: "literatur", ex: "English literature." },
    { eng: "little", idn: "kecil/sedikit", ex: "Little bit." },
    { eng: "live", idn: "hidup/tinggal", ex: "Live concert." },
    { eng: "liver", idn: "hati", ex: "Pig liver." },
    { eng: "living", idn: "hidup", ex: "Living room." },
    { eng: "load", idn: "muatan/memuat", ex: "Full load." },
    { eng: "loan", idn: "pinjaman", ex: "Bank loan." },
    { eng: "lobby", idn: "lobi", ex: "Hotel lobby." },
    { eng: "local", idn: "lokal", ex: "Local news." },
    { eng: "locate", idn: "menemukan", ex: "Locate the place." },
    { eng: "location", idn: "lokasi", ex: "GPS location." },
    { eng: "lock", idn: "mengunci", ex: "Lock the door." },
    { eng: "logical", idn: "logis", ex: "Logical thinking." },
    { eng: "lonely", idn: "kesepian", ex: "I feel lonely." },
    { eng: "long", idn: "panjang", ex: "Long hair." },
    { eng: "look", idn: "melihat", ex: "Look at me." },
    { eng: "loop", idn: "putaran", ex: "Feedback loop." },
    { eng: "loose", idn: "longgar", ex: "Loose shirt." },
    { eng: "lord", idn: "tuan/tuhan", ex: "Oh my Lord." },
    { eng: "lorry", idn: "truk", ex: "Driving a lorry." },
    { eng: "lose", idn: "hilang/kalah", ex: "Lose weight." },
    { eng: "loss", idn: "kerugian", ex: "Weight loss." },
    { eng: "lost", idn: "hilang", ex: "Get lost." },
    { eng: "lot", idn: "banyak", ex: "A lot of money." },
    { eng: "loud", idn: "keras", ex: "Loud music." },
    { eng: "lounge", idn: "ruang tunggu", ex: "Airport lounge." },
    { eng: "love", idn: "cinta", ex: "I love you." },
    { eng: "lovely", idn: "menyenangkan", ex: "Lovely day." },
    { eng: "low", idn: "rendah", ex: "Low battery." },
    { eng: "lower", idn: "menurunkan", ex: "Lower the volume." },
    { eng: "loyal", idn: "setia", ex: "Loyal customer." },
    { eng: "luck", idn: "keberuntungan", ex: "Good luck." },
    { eng: "lucky", idn: "beruntung", ex: "Lucky day." },
    { eng: "luggage", idn: "bagasi", ex: "Hand luggage." },
    { eng: "lump", idn: "benjolan", ex: "Sugar lump." },
    { eng: "lunch", idn: "makan siang", ex: "Eat lunch." },
    { eng: "lung", idn: "paru-paru", ex: "Left lung." },
    { eng: "luxury", idn: "mewah", ex: "Luxury car." },
    { eng: "machine", idn: "mesin", ex: "Washing machine." },
    { eng: "mad", idn: "gila/marah", ex: "Don't be mad." },
    { eng: "magazine", idn: "majalah", ex: "Fashion magazine." },
    { eng: "magic", idn: "sihir", ex: "Magic show." },
    { eng: "magical", idn: "ajaib", ex: "Magical place." },
    { eng: "magnet", idn: "magnet", ex: "Strong magnet." },
    { eng: "magnitude", idn: "besarnya", ex: "Magnitude of earthquake." },
    { eng: "maid", idn: "pembantu", ex: "House maid." },
    { eng: "mail", idn: "surat", ex: "Check mail." },
    { eng: "main", idn: "utama", ex: "Main street." },
    { eng: "mainstream", idn: "arus utama", ex: "Mainstream media." },
    { eng: "maintain", idn: "memelihara", ex: "Maintain health." },
    { eng: "maintenance", idn: "pemeliharaan", ex: "Under maintenance." },
    { eng: "major", idn: "utama/besar", ex: "Major city." },
    { eng: "majority", idn: "mayoritas", ex: "In the majority." },
    { eng: "make", idn: "membuat", ex: "Make a cake." },
    { eng: "male", idn: "laki-laki", ex: "The cat is male." },
    { eng: "mammal", idn: "mamalia", ex: "Whale is a mammal." },
    { eng: "man", idn: "pria", ex: "Old man." },
    { eng: "manage", idn: "mengelola", ex: "Manage time." },
    { eng: "management", idn: "manajemen", ex: "Hotel management." },
    { eng: "manager", idn: "manajer", ex: "Bank manager." },
    { eng: "manner", idn: "cara/sikap", ex: "Table manner." },
    { eng: "manual", idn: "manual", ex: "Read manual." },
    { eng: "manufacture", idn: "manufaktur", ex: "Factory manufacture." },
    { eng: "manufacturer", idn: "produsen", ex: "Car manufacturer." },
    { eng: "many", idn: "banyak", ex: "Many people." },
    { eng: "map", idn: "peta", ex: "World map." },
    { eng: "margin", idn: "margin/pinggir", ex: "Page margin." },
    { eng: "marine", idn: "laut/bahari", ex: "Marine life." },
    { eng: "mark", idn: "tanda/nilai", ex: "Check mark." },
    { eng: "market", idn: "pasar", ex: "Traditional market." },
    { eng: "marketing", idn: "pemasaran", ex: "Marketing plan." },
    { eng: "marriage", idn: "pernikahan", ex: "Long marriage." },
    { eng: "marry", idn: "menikah", ex: "Marry me." },
    { eng: "marvelous", idn: "menakjubkan", ex: "Marvelous view." },
    { eng: "mass", idn: "massa/misa", ex: "Mass media." },
    { eng: "massive", idn: "masif", ex: "Massive building." },
    { eng: "master", idn: "tuan/ahli", ex: "Master of art." },
    { eng: "match", idn: "cocok/pertandingan", ex: "Football match." },
    { eng: "mate", idn: "teman", ex: "Class mate." },
    { eng: "material", idn: "bahan", ex: "Building material." },
    { eng: "mathematics", idn: "matematika", ex: "Learn mathematics." },
    { eng: "matter", idn: "masalah", ex: "Does it matter?" },
    { eng: "maximum", idn: "maksimum", ex: "Maximum speed." },
    { eng: "maybe", idn: "mungkin", ex: "Maybe later." },
    { eng: "mayor", idn: "walikota", ex: "City mayor." },
    { eng: "meal", idn: "makanan", ex: "Healthy meal." },
    { eng: "mean", idn: "berarti/kejam", ex: "Don't be mean." },
    { eng: "meaning", idn: "arti", ex: "Deep meaning." },
    { eng: "measure", idn: "ukuran/tindakan", ex: "Measure height." },
    { eng: "measurement", idn: "pengukuran", ex: "Standard measurement." },
    { eng: "meat", idn: "daging", ex: "Eat meat." },
    { eng: "mechanical", idn: "mekanis", ex: "Mechanical engineer." },
    { eng: "mechanism", idn: "mekanisme", ex: "Defense mechanism." },
    { eng: "medal", idn: "medali", ex: "Gold medal." },
    { eng: "media", idn: "media", ex: "Social media." },
    { eng: "medical", idn: "medis", ex: "Medical school." },
    { eng: "medicine", idn: "obat", ex: "Take medicine." },
    { eng: "medium", idn: "medium/sedang", ex: "Size medium." },
    { eng: "meet", idn: "bertemu", ex: "Nice to meet you." },
    { eng: "meeting", idn: "pertemuan", ex: "Office meeting." },
    { eng: "melody", idn: "melodi", ex: "Beautiful melody." },
    { eng: "member", idn: "anggota", ex: "Family member." },
    { eng: "membership", idn: "keanggotaan", ex: "GYM membership." },
    { eng: "memory", idn: "ingatan", ex: "Good memory." },
    { eng: "mental", idn: "mental", ex: "Mental health." },
    { eng: "mention", idn: "menyebutkan", ex: "Don't mention it." },
    { eng: "menu", idn: "menu", ex: "Food menu." },
    { eng: "mercy", idn: "rahmat/belas kasihan", ex: "At your mercy." },
    { eng: "merely", idn: "hanya", ex: "Merely a friend." },
    { eng: "merit", idn: "jasa/patut", ex: "Merit scholarship." },
    { eng: "message", idn: "pesan", ex: "WhatsApp message." },
    { eng: "metal", idn: "logam", ex: "Heavy metal." },
    { eng: "metaphor", idn: "metafora", ex: "Deep metaphor." },
    { eng: "meter", idn: "meter", ex: "Ten meters." },
    { eng: "method", idn: "metode", ex: "Scientific method." },
    { eng: "microscope", idn: "mikroskop", ex: "Under microscope." },
    { eng: "middle", idn: "tengah", ex: "Middle East." },
    { eng: "might", idn: "mungkin/kekuatan", ex: "Might be rain." },
    { eng: "military", idn: "militer", ex: "Military service." },
    { eng: "milk", idn: "susu", ex: "Fresh milk." },
    { eng: "mill", idn: "penggilingan", ex: "Wind mill." },
    { eng: "million", idn: "juta", ex: "One million." },
    { eng: "mind", idn: "pikiran", ex: "Open mind." },
    { eng: "mine", idn: "milikku/tambang", ex: "Gold mine." },
    { eng: "mineral", idn: "mineral", ex: "Mineral water." },
    { eng: "minimum", idn: "minimum", ex: "Minimum wage." },
    { eng: "minister", idn: "menteri", ex: "Prime minister." },
    { eng: "minor", idn: "minor/kecil", ex: "Minor injury." },
    { eng: "minority", idn: "minoritas", ex: "Ethnic minority." },
    { eng: "minute", idn: "menit", ex: "Five minutes." },
    { eng: "miracle", idn: "mukjizat", ex: "I need a miracle." },
    { eng: "mirror", idn: "cermin", ex: "Look at mirror." },
    { eng: "miserable", idn: "menderita", ex: "I feel miserable." },
    { eng: "misery", idn: "penderitaan", ex: "Human misery." },
    { eng: "miss", idn: "rindu/luput", ex: "I miss you." },
    { eng: "mission", idn: "misi", ex: "Space mission." },
    { eng: "mistake", idn: "kesalahan", ex: "Common mistake." },
    { eng: "mix", idn: "campur", ex: "Mix the colors." },
    { eng: "mixture", idn: "campuran", ex: "Chemical mixture." },
    { eng: "mobile", idn: "mobile", ex: "Mobile phone." },
    { eng: "mode", idn: "mode", ex: "Silent mode." },
    { eng: "model", idn: "model", ex: "Fashion model." },
    { eng: "moderate", idn: "moderat", ex: "Moderate climate." },
    { eng: "modern", idn: "modern", ex: "Modern house." },
    { eng: "modest", idn: "sederhana", ex: "Be modest." },
    { eng: "modify", idn: "memodifikasi", ex: "Modify car." },
    { eng: "module", idn: "modul", ex: "Study module." },
    { eng: "moist", idn: "lembab", ex: "Moist cake." },
    { eng: "molecule", idn: "molekul", ex: "Water molecule." },
    { eng: "moment", idn: "momen", ex: "Wait a moment." },
    { eng: "money", idn: "uang", ex: "Spend money." },
    { eng: "monitor", idn: "monitor", ex: "Computer monitor." },
    { eng: "monster", idn: "monster", ex: "Scary monster." },
    { eng: "month", idn: "bulan", ex: "Next month." },
    { eng: "monthly", idn: "bulanan", ex: "Monthly report." },
    { eng: "monument", idn: "monumen", ex: "Historical monument." },
    { eng: "mood", idn: "suasana hati", ex: "In a bad mood." },
    { eng: "moon", idn: "bulan", ex: "Full moon." },
    { eng: "moral", idn: "moral", ex: "Moral support." },
    { eng: "more", idn: "lebih", ex: "One more." },
    { eng: "morning", idn: "pagi", ex: "Early morning." },
    { eng: "mortgage", idn: "hipotek", ex: "House mortgage." },
    { eng: "mostly", idn: "kebanyakan", ex: "Mostly sunny." },
    { eng: "mother", idn: "ibu", ex: "My mother." },
    { eng: "motion", idn: "gerak", ex: "Slow motion." },
    { eng: "motivate", idn: "memotivasi", ex: "Motivate students." },
    { eng: "motivation", idn: "motivasi", ex: "High motivation." },
    { eng: "motor", idn: "motor", ex: "Motor cycle." },
    { eng: "mountain", idn: "gunung", ex: "Everest mountain." },
    { eng: "mouse", idn: "tikus", ex: "Computer mouse." },
    { eng: "mouth", idn: "mulut", ex: "Shut your mouth." },
    { eng: "move", idn: "bergerak", ex: "Move on." },
    { eng: "movement", idn: "gerakan", ex: "Political movement." },
    { eng: "movie", idn: "film", ex: "Action movie." },
    { eng: "much", idn: "banyak", ex: "Much water." },
    { eng: "mud", idn: "lumpur", ex: "Play in the mud." },
    { eng: "multiple", idn: "ganda/banyak", ex: "Multiple choice." },
    { eng: "multiply", idn: "mengalikan", ex: "Five multiply two." },
    { eng: "murder", idn: "pembunuhan", ex: "Murder case." },
    { eng: "muscle", idn: "otot", ex: "Strong muscle." },
    { eng: "museum", idn: "museum", ex: "Visit museum." },
    { eng: "music", idn: "musik", ex: "Rock music." },
    { eng: "musical", idn: "musikal", ex: "Musical drama." },
    { eng: "musician", idn: "musisi", ex: "Famous musician." },
    { eng: "mutual", idn: "saling", ex: "Mutual friend." },
    { eng: "mystery", idn: "misteri", ex: "Murder mystery." },
    { eng: "myth", idn: "mitos", ex: "Greek myth." },
    { eng: "nail", idn: "paku/kuku", ex: "Finger nail." },
    { eng: "naked", idn: "telanjang", ex: "Naked truth." },
    { eng: "name", idn: "nama", ex: "Call my name." },
    { eng: "narrative", idn: "naratif", ex: "Personal narrative." },
    { eng: "narrow", idn: "sempit", ex: "Narrow road." },
    { eng: "nation", idn: "bangsa", ex: "One nation." },
    { eng: "national", idn: "nasional", ex: "National day." },
    { eng: "native", idn: "pribumi/asli", ex: "Native speaker." },
    { eng: "natural", idn: "alami", ex: "Natural beauty." },
    { eng: "nature", idn: "alam", ex: "Mother nature." },
    { eng: "navy", idn: "angkatan laut", ex: "Navy seal." },
    { eng: "near", idn: "dekat", ex: "Near me." },
    { eng: "nearby", idn: "disekitar", ex: "Nearby park." },
    { eng: "nearly", idn: "hampir", ex: "Nearly finished." },
    { eng: "neat", idn: "rapi", ex: "Neat hair." },
    { eng: "necessary", idn: "perlu", ex: "If necessary." },
    { eng: "neck", idn: "leher", ex: "Long neck." },
    { eng: "need", idn: "perlu", ex: "I need you." },
    { eng: "needle", idn: "jarum", ex: "Sewing needle." },
    { eng: "negative", idn: "negatif", ex: "Negative energy." },
    { eng: "neglect", idn: "mengabaikan", ex: "Neglect duties." },
    { eng: "negotiate", idn: "bernegosiasi", ex: "Negotiate salary." },
    { eng: "negotiation", idn: "negosiasi", ex: "Under negotiation." },
    { eng: "neighbour", idn: "tetangga", ex: "New neighbour." },
    { eng: "neither", idn: "tidak keduanya", ex: "Neither of them." },
    { eng: "nervous", idn: "gugup", ex: "Feel nervous." },
    { eng: "nest", idn: "sarang", ex: "Bird nest." },
    { eng: "net", idn: "jaring/netto", ex: "Fishing net." },
    { eng: "network", idn: "jaringan", ex: "Computer network." },
    { eng: "neutral", idn: "netral", ex: "Neutral gear." },
    { eng: "never", idn: "tidak pernah", ex: "Never say never." },
    { eng: "nevertheless", idn: "namun", ex: "Nevertheless, I go." },
    { eng: "new", idn: "baru", ex: "New car." },
    { eng: "newly", idn: "baru saja", ex: "Newly wed." },
    { eng: "news", idn: "berita", ex: "Breaking news." },
    { eng: "newspaper", idn: "koran", ex: "Daily newspaper." },
    { eng: "next", idn: "berikutnya", ex: "Next week." },
    { eng: "nice", idn: "bagus/baik", ex: "Nice try." },
    { eng: "night", idn: "malam", ex: "Good night." },
    { eng: "nightmare", idn: "mimpi buruk", ex: "I had a nightmare." },
    { eng: "nine", idn: "sembilan", ex: "Nine o'clock." },
    { eng: "noble", idn: "mulia", ex: "Noble man." },
    { eng: "nobody", idn: "tidak ada orang", ex: "Nobody knows." },
    { eng: "noise", idn: "kebisingan", ex: "Loud noise." },
    { eng: "noisy", idn: "berisik", ex: "Noisy children." },
    { eng: "nominate", idn: "mencalonkan", ex: "Nominate the leader." },
    { eng: "none", idn: "tidak ada", ex: "None of us." },
    { eng: "nonetheless", idn: "meskipun demikian", ex: "Nonetheless, wait." },
    { eng: "nonsense", idn: "omong kosong", ex: "What a nonsense." },
    { eng: "noon", idn: "siang", ex: "Twelve noon." },
    { eng: "nor", idn: "maupun tidak", ex: "Neither red nor blue." },
    { eng: "normal", idn: "normal", ex: "Normal day." },
    { eng: "normally", idn: "biasanya", ex: "Normally I go." },
    { eng: "north", idn: "utara", ex: "North Pole." },
    { eng: "nose", idn: "hidung", ex: "Long nose." },
    { eng: "not", idn: "tidak", ex: "I'm not ready." },
    { eng: "note", idn: "catatan", ex: "Sticky note." },
    { eng: "notebook", idn: "buku catatan", ex: "Spiral notebook." },
    { eng: "nothing", idn: "tidak ada apa-apa", ex: "Nothing to lose." },
    { eng: "notice", idn: "pemberitahuan", ex: "Public notice." },
    { eng: "notion", idn: "gagasan", ex: "Simple notion." },
    { eng: "noun", idn: "kata benda", ex: "Common noun." },
    { eng: "novel", idn: "novel", ex: "New novel." },
    { eng: "now", idn: "sekarang", ex: "Do it now." },
    { eng: "nowhere", idn: "tidak di mana pun", ex: "Nowhere to go." },
    { eng: "nuclear", idn: "nuklir", ex: "Nuclear energy." },
    { eng: "nuisance", idn: "gangguan", ex: "What a nuisance." },
    { eng: "number", idn: "nomor", ex: "Lucky number." },
    { eng: "numerous", idn: "banyak sekali", ex: "Numerous books." },
    { eng: "nurse", idn: "perawat", ex: "Hospital nurse." },
    { eng: "nut", idn: "kacang", ex: "Cashew nut." },
    { eng: "nutrition", idn: "nutrisi", ex: "Good nutrition." },
    { eng: "object", idn: "objek", ex: "Identify object." },
    { eng: "objection", idn: "keberatan", ex: "I have no objection." },
    { eng: "objective", idn: "tujuan/objektif", ex: "Main objective." },
    { eng: "obligation", idn: "kewajiban", ex: "Legal obligation." },
    { eng: "observation", idn: "observasi", ex: "Keep under observation." },
    { eng: "observe", idn: "mengamati", ex: "Observe the sky." },
    { eng: "obstacle", idn: "hambatan", ex: "Overcome obstacle." },
    { eng: "obtain", idn: "mendapatkan", ex: "Obtain permission." },
    { eng: "obvious", idn: "jelas", ex: "It's obvious." },
    { eng: "occasion", idn: "kesempatan/acara", ex: "Special occasion." },
    { eng: "occasional", idn: "sesekali", ex: "Occasional rain." },
    { eng: "occupation", idn: "pekerjaan", ex: "What is your occupation?" },
    { eng: "occupy", idn: "menempati", ex: "Occupy the room." },
    { eng: "occur", idn: "terjadi", ex: "Accidents occur." },
    { eng: "ocean", idn: "samudra", ex: "Blue ocean." },
    { eng: "o'clock", idn: "pukul", ex: "Eight o'clock." },
    { eng: "odd", idn: "aneh/ganjil", ex: "Odd number." },
    { eng: "offence", idn: "pelanggaran", ex: "Minor offence." },
    { eng: "offend", idn: "menyinggung", ex: "Don't offend him." },
    { eng: "offensive", idn: "ofensif/menghina", ex: "Offensive language." },
    { eng: "offer", idn: "tawaran", ex: "Special offer." },
    { eng: "office", idn: "kantor", ex: "Post office." },
    { eng: "officer", idn: "petugas/perwira", ex: "Police officer." },
    { eng: "official", idn: "resmi", ex: "Official website." },
    { eng: "often", idn: "sering", ex: "Often I go." },
    { eng: "oil", idn: "minyak", ex: "Cooking oil." },
    { eng: "old", idn: "tua", ex: "Old man." },
    { eng: "omit", idn: "menghilangkan", ex: "Omit the details." },
    { eng: "once", idn: "sekali", ex: "Once upon a time." },
    { eng: "one", idn: "satu", ex: "Number one." },
    { eng: "ongoing", idn: "sedang berlangsung", ex: "Ongoing project." },
    { eng: "online", idn: "online", ex: "Online shop." },
    { eng: "only", idn: "hanya", ex: "Only you." },
    { eng: "onto", idn: "keatas", ex: "Onto the roof." },
    { eng: "open", idn: "buka", ex: "Open door." },
    { eng: "opening", idn: "pembukaan", ex: "Grand opening." },
    { eng: "operate", idn: "mengoperasikan", ex: "Operate machine." },
    { eng: "operation", idn: "operasi", ex: "Army operation." },
    { eng: "opinion", idn: "pendapat", ex: "In my opinion." },
    { eng: "opponent", idn: "lawan", ex: "Beat the opponent." },
    { eng: "opportunity", idn: "kesempatan", ex: "Job opportunity." },
    { eng: "oppose", idn: "menentang", ex: "Oppose the law." },
    { eng: "opposite", idn: "berlawanan", ex: "Opposite side." },
    { eng: "opposition", idn: "oposisi", ex: "Political opposition." },
    { eng: "option", idn: "pilihan", ex: "Menu option." },
    { eng: "orange", idn: "jeruk/oranye", ex: "Orange juice." },
    { eng: "orbit", idn: "orbit", ex: "Earth orbit." },
    { eng: "order", idn: "pesanan/perintah", ex: "Order food." },
    { eng: "ordinary", idn: "biasa", ex: "Ordinary people." },
    { eng: "organ", idn: "organ", ex: "Body organ." },
    { eng: "organic", idn: "organik", ex: "Organic food." },
    { eng: "organisation", idn: "organisasi", ex: "World organisation." },
    { eng: "organise", idn: "mengatur", ex: "Organise a trip." },
    { eng: "origin", idn: "asal", ex: "Point of origin." },
    { eng: "original", idn: "asli", ex: "Original document." },
    { eng: "other", idn: "lain", ex: "Other people." },
    { eng: "otherwise", idn: "sebaliknya", ex: "Hurry up, otherwise late." },
    { eng: "ought", idn: "seharusnya", ex: "You ought to go." },
    { eng: "ounce", idn: "ons", ex: "One ounce." },
    { eng: "our", idn: "kita punya", ex: "Our car." },
    { eng: "out", idn: "keluar", ex: "Go out." },
    { eng: "outcome", idn: "hasil", ex: "Final outcome." },
    { eng: "outdoor", idn: "luar ruangan", ex: "Outdoor activity." },
    { eng: "outer", idn: "luar", ex: "Outer space." },
    { eng: "outline", idn: "garis besar", ex: "Essay outline." },
    { eng: "output", idn: "output/hasil", ex: "Product output." },
    { eng: "outside", idn: "diluar", ex: "Play outside." },
    { eng: "outstanding", idn: "luar biasa", ex: "Outstanding performance." },
    { eng: "oven", idn: "oven", ex: "Pizza oven." },
    { eng: "over", idn: "diatas/lebih", ex: "Over the moon." },
    { eng: "overall", idn: "secara keseluruhan", ex: "Overall good." },
    { eng: "overcome", idn: "mengatasi", ex: "Overcome fear." },
    { eng: "overlook", idn: "mengabaikan", ex: "Don't overlook details." },
    { eng: "overseas", idn: "luar negeri", ex: "Study overseas." },
    { eng: "owe", idn: "berhutang", ex: "I owe you." },
    { eng: "own", idn: "milik sendiri", ex: "My own car." },
    { eng: "owner", idn: "pemilik", ex: "Shop owner." },
    { eng: "oxide", idn: "oksida", ex: "Iron oxide." },
    { eng: "oxygen", idn: "oksigen", ex: "Need oxygen." }
];
